package zinc;

enum TokKind {
  IDENT, INT_LIT, FLOAT_LIT, STR_LIT, FSTR_LIT,
  KW_IMPORT, KW_VAR, KW_FOR, KW_WHILE, KW_IF, KW_ELSE, KW_RETURN,
  KW_TRUE, KW_FALSE, KW_BREAK, KW_CONTINUE,
  LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, COMMA, DOT, COLON, SEMI, QUESTION,
  ASSIGN, PLUS_EQ, MINUS_EQ, STAR_EQ,
  PLUS, MINUS, STAR, SLASH, PERCENT, BANG,
  PLUS_PLUS, MINUS_MINUS,
  AMP_AMP, PIPE_PIPE, ARROW,
  EQ, NE, LT, GT, LE, GE,
  EOF,
}
