package zinc;

enum TokKind {
  IDENT, INT_LIT, FLOAT_LIT, STR_LIT,
  KW_FN, KW_VAR, KW_FOR, KW_IN, KW_WHILE, KW_IF, KW_ELSE, KW_RETURN, KW_STRUCT,
  KW_TRUE, KW_FALSE, KW_BREAK, KW_CONTINUE,
  LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, COMMA, DOT, COLON,
  ASSIGN, PLUS_EQ, MINUS_EQ, STAR_EQ,
  PLUS, MINUS, STAR, SLASH, PERCENT, BANG,
  AMP_AMP, PIPE_PIPE,
  EQ, NE, LT, GT, LE, GE,
  DOT_DOT,
  EOF,
}
