// Copyright 2026 victorybhg
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// runPack packages a .zn file for deployment.
// Formats: pyinstaller (default), docker, pex
func runPack(znFile string, format string) {
	// First transpile to .py
	base := strings.TrimSuffix(filepath.Base(znFile), ".zn")
	pyFile := base + ".py"
	_, _, err := transpileV2File(znFile, pyFile, false)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	pythonBin := findPython()

	switch format {
	case "", "pyinstaller":
		packPyInstaller(pyFile, base, pythonBin)
	case "docker":
		packDocker(pyFile, base)
	case "k8s":
		packDocker(pyFile, base)
		packK8s(base)
	default:
		fmt.Fprintf(os.Stderr, "unknown format: %s (use: pyinstaller, docker, k8s)\n", format)
		os.Exit(1)
	}
}

// packPyInstaller creates a single-file executable using PyInstaller.
// Points PyInstaller at the free-threaded Python interpreter.
func packPyInstaller(pyFile, name, pythonBin string) {
	fmt.Printf("packing %s with PyInstaller (using %s)...\n", pyFile, pythonBin)

	// Generate PyInstaller spec that uses the free-threaded interpreter
	spec := fmt.Sprintf(`# Generated by zinc pack — uses free-threaded Python
import PyInstaller.__main__
import sys

PyInstaller.__main__.run([
    '%s',
    '--onefile',
    '--name', '%s',
    '--distpath', 'dist',
    '--clean',
])
`, pyFile, name)

	specFile := name + "_pack.py"
	if err := os.WriteFile(specFile, []byte(spec), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing spec: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("  run: %s %s\n", pythonBin, specFile)
	fmt.Printf("  output: dist/%s\n", name)
	fmt.Println("\nTo build:")
	fmt.Printf("  %s -m pip install pyinstaller  # if not installed\n", pythonBin)
	fmt.Printf("  %s %s\n", pythonBin, specFile)
}

// packDocker generates a Dockerfile using free-threaded Python base image.
func packDocker(pyFile, name string) {
	dockerfile := fmt.Sprintf(`# Generated by zinc pack — free-threaded Python
FROM python:3.14-slim

# Enable free-threading (GIL disabled)
ENV PYTHON_GIL=0

WORKDIR /app
COPY %s .

# Install dependencies if requirements.txt exists
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi

CMD ["python3", "%s"]
`, pyFile, pyFile)

	if err := os.WriteFile("Dockerfile", []byte(dockerfile), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing Dockerfile: %v\n", err)
		os.Exit(1)
	}

	// Generate .dockerignore
	dockerignore := `*.zn
*.go
__pycache__
.git
dist
build
`
	os.WriteFile(".dockerignore", []byte(dockerignore), 0644)

	fmt.Printf("generated Dockerfile for %s\n", name)
	fmt.Println("\nTo build and run:")
	fmt.Printf("  docker build -t %s .\n", name)
	fmt.Printf("  docker run %s\n", name)
}

// packK8s generates a K8s deployment manifest.
func packK8s(name string) {
	manifest := fmt.Sprintf(`# Generated by zinc pack — K8s deployment with free-threaded Python
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %s
  labels:
    app: %s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %s
  template:
    metadata:
      labels:
        app: %s
    spec:
      containers:
      - name: %s
        image: %s:latest
        env:
        - name: PYTHON_GIL
          value: "0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
`, name, name, name, name, name, name)

	k8sFile := name + "-deployment.yaml"
	if err := os.WriteFile(k8sFile, []byte(manifest), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing k8s manifest: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s\n", k8sFile)
	fmt.Println("\nTo deploy:")
	fmt.Printf("  kubectl apply -f %s\n", k8sFile)
}
