// Copyright 2026 victorybhg
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"zinc/internal/lexer"
	"zinc/internal/parser"
)

// runPack packages a .zn file or project directory for deployment.
// Formats: pyinstaller (default), docker, k8s
func runPack(target string, format string) {
	info, err := os.Stat(target)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var pyFiles []string
	var entryPoint string
	var projectDir string
	var name string

	if info.IsDir() {
		// Project directory — transpile all .zn files
		projectDir = target
		name = filepath.Base(target)
		if name == "." {
			name, _ = os.Getwd()
			name = filepath.Base(name)
		}
		znFiles, _ := filepath.Glob(filepath.Join(target, "*.zn"))
		if len(znFiles) == 0 {
			fmt.Fprintf(os.Stderr, "error: no .zn files found in %s\n", target)
			os.Exit(1)
		}
		for _, zn := range znFiles {
			base := strings.TrimSuffix(filepath.Base(zn), ".zn")
			pyFile := base + ".py"
			_, _, err := transpileV2File(zn, pyFile, false)
			if err != nil {
				fmt.Fprintf(os.Stderr, "error transpiling %s: %v\n", zn, err)
				os.Exit(1)
			}
			pyFiles = append(pyFiles, pyFile)
			// Entry point: main.zn > app.zn > first file
			if base == "main" || base == "app" {
				entryPoint = pyFile
			}
		}
		if entryPoint == "" {
			entryPoint = pyFiles[0]
		}
		fmt.Printf("transpiled %d .zn files → .py\n", len(pyFiles))
	} else {
		// Single file
		name = strings.TrimSuffix(filepath.Base(target), ".zn")
		pyFile := name + ".py"
		_, _, err := transpileV2File(target, pyFile, false)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error: %v\n", err)
			os.Exit(1)
		}
		pyFiles = []string{pyFile}
		entryPoint = pyFile
		projectDir = "."
	}

	// Auto-generate requirements.txt from imports (if not already present)
	if _, err := os.Stat("requirements.txt"); os.IsNotExist(err) {
		var allDeps []string
		// Parse each .zn file to extract third-party deps
		var znFilesToScan []string
		if info.IsDir() {
			znFilesToScan, _ = filepath.Glob(filepath.Join(target, "*.zn"))
		} else {
			znFilesToScan = []string{target}
		}
		for _, zn := range znFilesToScan {
			src, _ := os.ReadFile(zn)
			lex := lexer.New(string(src))
			tokens := lex.Tokenize()
			p := parser.New(tokens)
			prog := p.ParseV2()
			allDeps = append(allDeps, extractDeps(prog)...)
		}
		// Deduplicate
		seen := make(map[string]bool)
		var uniqueDeps []string
		for _, d := range allDeps {
			if !seen[d] {
				seen[d] = true
				uniqueDeps = append(uniqueDeps, d)
			}
		}
		if len(uniqueDeps) > 0 {
			reqs := generateRequirements(uniqueDeps)
			os.WriteFile("requirements.txt", []byte(reqs), 0644)
			fmt.Printf("generated requirements.txt: %s\n", strings.Join(uniqueDeps, ", "))
		}
	} else {
		fmt.Println("using existing requirements.txt")
	}

	pythonBin := findPython()

	switch format {
	case "", "pyinstaller":
		packPyInstaller(entryPoint, name, pythonBin, pyFiles)
	case "nuitka":
		packNuitka(entryPoint, name, pythonBin, pyFiles)
	case "docker":
		packDocker(entryPoint, name, pyFiles, projectDir)
	case "k8s":
		packDocker(entryPoint, name, pyFiles, projectDir)
		packK8s(name)
	default:
		fmt.Fprintf(os.Stderr, "unknown format: %s (use: pyinstaller, nuitka, docker, k8s)\n", format)
		os.Exit(1)
	}
}

// packPyInstaller creates a single-file executable using PyInstaller.
func packPyInstaller(entryPoint, name, pythonBin string, pyFiles []string) {
	fmt.Printf("packing %s with PyInstaller (using %s)...\n", entryPoint, pythonBin)

	// Collect additional data files
	var addData []string
	for _, f := range pyFiles {
		if f != entryPoint {
			addData = append(addData, fmt.Sprintf("    '--add-data', '%s:.',", f))
		}
	}
	// Include requirements.txt if exists
	if _, err := os.Stat("requirements.txt"); err == nil {
		addData = append(addData, "    '--hidden-import', 'pkg_resources',")
	}

	addDataStr := ""
	if len(addData) > 0 {
		addDataStr = "\n" + strings.Join(addData, "\n")
	}

	spec := fmt.Sprintf(`# Generated by zinc pack — uses free-threaded Python
import PyInstaller.__main__

PyInstaller.__main__.run([
    '%s',
    '--onefile',
    '--name', '%s',
    '--distpath', 'dist',
    '--clean',%s
])
`, entryPoint, name, addDataStr)

	specFile := name + "_pack.py"
	if err := os.WriteFile(specFile, []byte(spec), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing spec: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("  entry point: %s\n", entryPoint)
	fmt.Printf("  output: dist/%s\n", name)
	fmt.Println("\nTo build:")
	fmt.Printf("  %s -m pip install pyinstaller  # if not installed\n", pythonBin)
	fmt.Printf("  %s %s\n", pythonBin, specFile)
}

// packNuitka compiles Python to native binary via Nuitka (Python → C → machine code).
// Produces a ~30-50% faster binary than CPython with full library compatibility.
func packNuitka(entryPoint, name, pythonBin string, pyFiles []string) {
	fmt.Printf("packing %s with Nuitka (using %s)...\n", entryPoint, pythonBin)

	// Build nuitka command args
	args := []string{
		"-m", "nuitka",
		"--onefile",
		fmt.Sprintf("--output-filename=%s", name),
		"--output-dir=dist",
		"--remove-output",
	}

	// Include additional .py files
	for _, f := range pyFiles {
		if f != entryPoint {
			args = append(args, fmt.Sprintf("--include-data-files=%s=./%s", f, f))
		}
	}

	// Follow imports for full compatibility
	args = append(args, "--follow-imports")
	args = append(args, entryPoint)

	fmt.Printf("  entry point: %s\n", entryPoint)
	fmt.Printf("  output: dist/%s\n", name)
	fmt.Println("\nTo build:")
	fmt.Printf("  %s -m pip install nuitka  # if not installed\n", pythonBin)
	fmt.Printf("  %s %s\n", pythonBin, strings.Join(args, " "))
	fmt.Println("\nNote: Nuitka compiles Python → C → machine code.")
	fmt.Println("      Requires a C compiler (gcc/clang/msvc).")
	fmt.Println("      First build takes longer, ~30-50%% faster at runtime.")

	// Also write a build script for convenience
	script := fmt.Sprintf(`#!/bin/bash
# Generated by zinc pack --format nuitka
# Compiles %s to native binary via Nuitka (Python → C → machine code)
set -e

# Install Nuitka if needed
%s -m pip install nuitka 2>/dev/null || true

# Compile
%s %s

echo "Built: dist/%s"
`, entryPoint, pythonBin, pythonBin, strings.Join(args, " "), name)

	scriptFile := "build-" + name + ".sh"
	if err := os.WriteFile(scriptFile, []byte(script), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error writing build script: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("\nOr run: ./%s\n", scriptFile)
}

// packDocker generates a Dockerfile for the project.
func packDocker(entryPoint, name string, pyFiles []string, projectDir string) {
	// Build COPY lines for all .py files
	var copyLines []string
	for _, f := range pyFiles {
		copyLines = append(copyLines, fmt.Sprintf("COPY %s .", f))
	}

	// Check for extra files to include
	extras := []string{"requirements.txt", "config.json", "config.yaml", "config.toml", ".env"}
	for _, extra := range extras {
		path := extra
		if projectDir != "." && projectDir != "" {
			path = filepath.Join(projectDir, extra)
		}
		if _, err := os.Stat(path); err == nil {
			copyLines = append(copyLines, fmt.Sprintf("COPY %s .", extra))
		}
	}

	dockerfile := fmt.Sprintf(`# Generated by zinc pack — free-threaded Python
# Build the free-threaded Python runtime from source
FROM python:3.14-slim AS base

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential wget && rm -rf /var/lib/apt/lists/*

# Download and build free-threaded Python
RUN wget -q https://www.python.org/ftp/python/3.14.3/Python-3.14.3.tar.xz && \
    tar xf Python-3.14.3.tar.xz && \
    cd Python-3.14.3 && \
    ./configure --prefix=/opt/python3t --disable-gil --enable-optimizations --quiet && \
    make -j$(nproc) --quiet && \
    make install --quiet && \
    cd / && rm -rf Python-3.14.3*

# Production image
FROM python:3.14-slim

# Copy free-threaded Python
COPY --from=base /opt/python3t /opt/python3t
ENV PATH="/opt/python3t/bin:$PATH"
ENV PYTHON_GIL=0

WORKDIR /app

# Copy project files
%s

# Install dependencies using free-threaded Python
RUN if [ -f requirements.txt ]; then /opt/python3t/bin/pip3 install --no-cache-dir -r requirements.txt; fi

CMD ["/opt/python3t/bin/python3", "%s"]
`, strings.Join(copyLines, "\n"), entryPoint)

	if err := os.WriteFile("Dockerfile", []byte(dockerfile), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing Dockerfile: %v\n", err)
		os.Exit(1)
	}

	dockerignore := `*.zn
*.go
__pycache__
.git
dist
build
*.pyc
`
	os.WriteFile(".dockerignore", []byte(dockerignore), 0644)

	fmt.Printf("generated Dockerfile for %s (%d files)\n", name, len(pyFiles))
	fmt.Println("\nTo build and run:")
	fmt.Printf("  docker build -t %s .\n", name)
	fmt.Printf("  docker run %s\n", name)
}

// packK8s generates a K8s deployment manifest.
func packK8s(name string) {
	manifest := fmt.Sprintf(`# Generated by zinc pack — K8s deployment with free-threaded Python
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %s
  labels:
    app: %s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %s
  template:
    metadata:
      labels:
        app: %s
    spec:
      containers:
      - name: %s
        image: %s:latest
        env:
        - name: PYTHON_GIL
          value: "0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
`, name, name, name, name, name, name)

	k8sFile := name + "-deployment.yaml"
	if err := os.WriteFile(k8sFile, []byte(manifest), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing k8s manifest: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated %s\n", k8sFile)
	fmt.Println("\nTo deploy:")
	fmt.Printf("  kubectl apply -f %s\n", k8sFile)
}
