# Generated by zinc pack — free-threaded Python
FROM python:3.14-slim

# Free-threading enabled — GIL disabled for true parallelism
ENV PYTHON_GIL=0

WORKDIR /app

# Copy project files
COPY classes.py .
COPY closures.py .
COPY collections.py .
COPY constants.py .
COPY data_processing.py .
COPY defaults_and_named_args.py .
COPY enums.py .
COPY error_handling.py .
COPY generators.py .
COPY hello.py .
COPY polars_pipeline.py .
COPY type_checking.py .
COPY variadic.py .

# Install dependencies
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi

CMD ["python3", "classes.py"]
