// Copyright 2026 victorybhg
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package pyfront

import "strings"

// FFIRuntimeFileName is the emitted cgo file that embeds CPython. It is only
// written when the program imports a module the front-end routes through FFI,
// so a pure-language program never links libpython.
const FFIRuntimeFileName = "zincpy_ffi.go"

// GlobalDeclsFileName is where the driver writes Meta.GlobalDecls (function
// decorator package-level rebinds), when non-empty.
const GlobalDeclsFileName = "zincpy_decls.go"

// FFIRuntime returns the Go source of the embedded-CPython FFI shim. The cgo
// compile/link flags are host-specific (Python include dir, libpython
// location), so the driver computes them from python3-config and passes them
// in as cflags/ldflags.
//
// The shim talks to libpython through the stable C API via <Python.h>. It only
// calls real exported functions (never C macros, which cgo cannot invoke) —
// e.g. Py_DecRef not Py_DECREF, PyObject_IsInstance against cached builtin
// type objects instead of the PyList_Check etc. macros. It marshals Go scalars
// and containers to/from CPython objects, and turns any Python exception into
// a panic(zincpyExc{...}) so it flows through the same try/except machinery as
// native raises.
//
// Concurrency: Py_InitializeEx runs once on a locked OS thread, then the GIL
// is released so each call can re-acquire it via PyGILState_Ensure; a mutex
// serializes calls (the generated programs are sequential).
func FFIRuntime(cflags, ldflags string) string {
	s := strings.Replace(ffiRuntimeTemplate, "__CFLAGS__", cflags, 1)
	return strings.Replace(s, "__LDFLAGS__", ldflags, 1)
}

const ffiRuntimeTemplate = `// Code generated by zincpy. DO NOT EDIT.
package main

/*
#cgo CFLAGS: __CFLAGS__
#cgo LDFLAGS: __LDFLAGS__
#include <stdlib.h>
#include <Python.h>

// cgo cannot call variadic C functions (Py_BuildValue) or C macros
// (Py_RETURN_NONE). Wrap the one we need in a plain function: a fresh
// reference to Python's None.
static PyObject* zpyNone(void) { Py_RETURN_NONE; }
*/
import "C"

import (
	"reflect"
	"runtime"
	"sync"
	"unsafe"
)

var (
	zpyOnce  sync.Once
	zpyMu    sync.Mutex
	zpyMods  = map[string]*C.PyObject{}
	zpyTypes = map[string]*C.PyObject{}
)

func zpyEnsureInit() {
	zpyOnce.Do(func() {
		runtime.LockOSThread()
		C.Py_InitializeEx(0) // skip signal handlers — we are embedded
		bm := C.PyImport_ImportModule(C.CString("builtins"))
		for _, name := range []string{"bool", "int", "float", "str", "list", "dict"} {
			cn := C.CString(name)
			zpyTypes[name] = C.PyObject_GetAttrString(bm, cn)
			C.free(unsafe.Pointer(cn))
		}
		C.PyEval_SaveThread() // release the GIL; each call re-acquires via GILState
	})
}

func zpyStrOf(o *C.PyObject) string {
	s := C.PyObject_Str(o)
	if s == nil {
		return ""
	}
	defer C.Py_DecRef(s)
	return C.GoString(C.PyUnicode_AsUTF8(s))
}

// zpyCheckErr turns a pending CPython exception into a panic(zincpyExc{...}) so
// it is catchable by a Python try/except in the compiled program.
func zpyCheckErr() {
	if C.PyErr_Occurred() == nil {
		return
	}
	var typ, val, tb *C.PyObject
	C.PyErr_Fetch(&typ, &val, &tb)
	C.PyErr_NormalizeException(&typ, &val, &tb)
	typeName := "Exception"
	if typ != nil {
		cn := C.CString("__name__")
		n := C.PyObject_GetAttrString(typ, cn)
		C.free(unsafe.Pointer(cn))
		if n != nil {
			typeName = C.GoString(C.PyUnicode_AsUTF8(n))
			C.Py_DecRef(n)
		}
	}
	msg := ""
	if val != nil {
		msg = zpyStrOf(val)
	}
	C.PyErr_Clear()
	panic(zincpyExc{Type: typeName, Msg: msg})
}

func zpyIsInst(o *C.PyObject, typ string) bool {
	t := zpyTypes[typ]
	return t != nil && C.PyObject_IsInstance(o, t) == 1
}

// zpyToPy converts a Go value to a new CPython object reference.
func zpyToPy(v any) *C.PyObject {
	switch x := v.(type) {
	case bool:
		n := C.long(0)
		if x {
			n = 1
		}
		return C.PyBool_FromLong(n)
	case int:
		return C.PyLong_FromLong(C.long(x))
	case float64:
		return C.PyFloat_FromDouble(C.double(x))
	case string:
		cs := C.CString(x)
		defer C.free(unsafe.Pointer(cs))
		return C.PyUnicode_FromString(cs)
	case *zincpyDict:
		d := C.PyDict_New()
		for _, k := range x.keys {
			pk := zpyToPy(k)
			pv := zpyToPy(x.vals[k])
			C.PyDict_SetItem(d, pk, pv)
			C.Py_DecRef(pk)
			C.Py_DecRef(pv)
		}
		return d
	default:
		// Any slice kind ([]any, []int, []string, ...) → a Python list. The
		// front-end types homogeneous list literals as concrete Go slices, so
		// reflection is needed to cover them all.
		rv := reflect.ValueOf(v)
		if rv.IsValid() && rv.Kind() == reflect.Slice {
			lst := C.PyList_New(C.Py_ssize_t(rv.Len()))
			for i := 0; i < rv.Len(); i++ {
				C.PyList_SetItem(lst, C.Py_ssize_t(i), zpyToPy(rv.Index(i).Interface())) // steals ref
			}
			return lst
		}
		return C.zpyNone()
	}
}

// zpyToGo converts a borrowed/owned CPython object to a native Go value. bool
// is checked before int because Python's bool is a subclass of int.
func zpyToGo(o *C.PyObject) any {
	switch {
	case o == nil:
		return nil
	case zpyIsInst(o, "bool"):
		return C.PyLong_AsLong(o) != 0
	case zpyIsInst(o, "int"):
		return int(C.PyLong_AsLong(o))
	case zpyIsInst(o, "float"):
		return float64(C.PyFloat_AsDouble(o))
	case zpyIsInst(o, "str"):
		return C.GoString(C.PyUnicode_AsUTF8(o))
	case zpyIsInst(o, "list"):
		n := int(C.PyList_Size(o))
		out := make([]any, n)
		for i := 0; i < n; i++ {
			out[i] = zpyToGo(C.PyList_GetItem(o, C.Py_ssize_t(i)))
		}
		return out
	case zpyIsInst(o, "dict"):
		keys := C.PyDict_Keys(o)
		defer C.Py_DecRef(keys)
		n := int(C.PyList_Size(keys))
		d := zincpyNewDict()
		for i := 0; i < n; i++ {
			k := C.PyList_GetItem(keys, C.Py_ssize_t(i))
			d.Set(zpyToGo(k), zpyToGo(C.PyDict_GetItem(o, k)))
		}
		return d
	default:
		return zpyStrOf(o)
	}
}

func zpyImport(name string) *C.PyObject {
	if m, ok := zpyMods[name]; ok {
		return m
	}
	cn := C.CString(name)
	defer C.free(unsafe.Pointer(cn))
	m := C.PyImport_ImportModule(cn)
	zpyCheckErr()
	zpyMods[name] = m
	return m
}

// zincpyPyImport loads a module for its import side effects (and to surface
// ImportError as a catchable exception at the import site).
func zincpyPyImport(name string) {
	zpyEnsureInit()
	zpyMu.Lock()
	defer zpyMu.Unlock()
	gil := C.PyGILState_Ensure()
	defer C.PyGILState_Release(gil)
	zpyImport(name)
}

// zincpyPyCall invokes module.fn(args...) in CPython and returns the result as
// a native Go value.
func zincpyPyCall(module, fn string, args ...any) any {
	zpyEnsureInit()
	zpyMu.Lock()
	defer zpyMu.Unlock()
	gil := C.PyGILState_Ensure()
	defer C.PyGILState_Release(gil)

	mod := zpyImport(module)
	cf := C.CString(fn)
	callable := C.PyObject_GetAttrString(mod, cf)
	C.free(unsafe.Pointer(cf))
	zpyCheckErr()
	tup := C.PyTuple_New(C.Py_ssize_t(len(args)))
	for i, a := range args {
		C.PyTuple_SetItem(tup, C.Py_ssize_t(i), zpyToPy(a))
	}
	res := C.PyObject_CallObject(callable, tup)
	C.Py_DecRef(tup)
	C.Py_DecRef(callable)
	zpyCheckErr()
	out := zpyToGo(res)
	C.Py_DecRef(res)
	return out
}

// zincpyPyGet reads module.attr from CPython as a native Go value.
func zincpyPyGet(module, attr string) any {
	zpyEnsureInit()
	zpyMu.Lock()
	defer zpyMu.Unlock()
	gil := C.PyGILState_Ensure()
	defer C.PyGILState_Release(gil)
	mod := zpyImport(module)
	ca := C.CString(attr)
	o := C.PyObject_GetAttrString(mod, ca)
	C.free(unsafe.Pointer(ca))
	zpyCheckErr()
	out := zpyToGo(o)
	C.Py_DecRef(o)
	return out
}
`
