// Copyright 2026 victorybhg
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package pyfront

// RuntimeFileName is the name of the emitted Python-runtime shim file.
const RuntimeFileName = "zincpy_runtime.go"

// RuntimeGo is the Go source of the Python-runtime shim. It is emitted as a
// sibling file in the output module (package main) and provides the handful
// of functions the front-end lowers divergent Python semantics into. Keeping
// it as emitted source — rather than a Go-side dependency — means the output
// module stays self-contained and the helpers are visible in `--emit`.
//
// Every import here is used by a function body, so an output program that
// happens not to call a given helper still compiles (unused funcs are legal
// in Go; unused imports are not).
const RuntimeGo = `// Code generated by zincpy. DO NOT EDIT.
package main

import (
	"cmp"
	"fmt"
	"math"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// zincpyPrint mirrors Python's print() for one value: Python str()
// formatting, newline-terminated.
func zincpyPrint(v any) {
	fmt.Println(zincpyStr(v))
}

// zincpyFormat implements format(value, spec) / an f-string {value:spec} field
// for the common subset of Python's format mini-language:
//
//	[[fill]align][sign][#][0][width][grouping][.precision][type]
//
// align <>^= , sign +- space, grouping , or _, the int types b/o/d/x/X, the
// float types e/E/f/F/g/G/%, and string s. Unsupported pieces fall back as
// closely as possible rather than diverging silently.
func zincpyFormat(v any, spec string) string {
	f := parseFormatSpec(spec)
	// String values (and an explicit s type) only honor fill/align/width.
	if s, ok := v.(string); ok || f.typ == 's' {
		if !ok {
			s = zincpyStr(v)
		}
		if f.align == 0 {
			f.align = '<' // strings default to left-aligned
		}
		return f.pad(s)
	}
	switch f.typ {
	case 'b', 'o', 'x', 'X', 'd', 'c':
		return f.formatInt(v)
	case 'e', 'E', 'f', 'F', 'g', 'G', '%':
		return f.formatFloat(v)
	}
	// No explicit type: pick by the value's runtime type.
	if _, ok := zincpyIntish(v); ok {
		return f.formatInt(v)
	}
	if _, ok := zincpyNum(v); ok {
		return f.formatFloat(v)
	}
	return f.pad(zincpyStr(v))
}

type formatSpec struct {
	fill      rune
	align     rune // '<' '>' '^' '=' or 0
	sign      byte // '+' '-' ' ' or 0
	alt       bool // '#'
	zero      bool // '0' pad
	width     int
	grouping  byte // ',' '_' or 0
	precision int  // -1 if absent
	typ       byte // format type or 0
}

func parseFormatSpec(spec string) formatSpec {
	f := formatSpec{fill: ' ', precision: -1}
	r := []rune(spec)
	i := 0
	// [fill]align: align is one of <>^= ; a fill char precedes it.
	if len(r) >= 2 && isAlign(r[1]) {
		f.fill = r[0]
		f.align = r[1]
		i = 2
	} else if len(r) >= 1 && isAlign(r[0]) {
		f.align = r[0]
		i = 1
	}
	if i < len(r) && (r[i] == '+' || r[i] == '-' || r[i] == ' ') {
		f.sign = byte(r[i])
		i++
	}
	if i < len(r) && r[i] == '#' {
		f.alt = true
		i++
	}
	if i < len(r) && r[i] == '0' {
		f.zero = true
		if f.align == 0 {
			f.align = '=' // '0' implies zero-pad after the sign
			f.fill = '0'
		}
		i++
	}
	for i < len(r) && r[i] >= '0' && r[i] <= '9' {
		f.width = f.width*10 + int(r[i]-'0')
		i++
	}
	if i < len(r) && (r[i] == ',' || r[i] == '_') {
		f.grouping = byte(r[i])
		i++
	}
	if i < len(r) && r[i] == '.' {
		i++
		f.precision = 0
		for i < len(r) && r[i] >= '0' && r[i] <= '9' {
			f.precision = f.precision*10 + int(r[i]-'0')
			i++
		}
	}
	if i < len(r) {
		f.typ = byte(r[i])
	}
	return f
}

func isAlign(r rune) bool { return r == '<' || r == '>' || r == '^' || r == '=' }

// pad applies fill/align/width to an already-rendered body (no sign handling).
func (f formatSpec) pad(s string) string {
	gap := f.width - utf8.RuneCountInString(s)
	if gap <= 0 {
		return s
	}
	fill := string(f.fill)
	switch f.align {
	case '>', '=':
		return strings.Repeat(fill, gap) + s
	case '^':
		left := gap / 2
		return strings.Repeat(fill, left) + s + strings.Repeat(fill, gap-left)
	default: // '<' or 0
		return s + strings.Repeat(fill, gap)
	}
}

// padNumeric applies width to a signed numeric body. With align '=' (or a '0'
// flag) the fill goes between the sign and the digits; otherwise it pads the
// whole field.
func (f formatSpec) padNumeric(sign, body string) string {
	if f.align == '=' || (f.zero && f.align == 0) {
		gap := f.width - utf8.RuneCountInString(sign) - utf8.RuneCountInString(body)
		if gap > 0 {
			return sign + strings.Repeat(string(f.fill), gap) + body
		}
		return sign + body
	}
	if f.align == 0 {
		f.align = '>' // numbers default to right-aligned
	}
	return f.pad(sign + body)
}

// signStr returns the leading sign string for a non-negative value given the
// sign flag ('+' forces '+', ' ' forces a space, otherwise empty).
func (f formatSpec) signStr(neg bool) string {
	if neg {
		return "-"
	}
	switch f.sign {
	case '+':
		return "+"
	case ' ':
		return " "
	}
	return ""
}

func (f formatSpec) formatInt(v any) string {
	n, ok := zincpyIntish(v)
	if !ok {
		if fv, ok := zincpyNum(v); ok {
			n = int(fv)
		}
	}
	neg := n < 0
	u := n
	if neg {
		u = -u
	}
	var body, prefix string
	switch f.typ {
	case 'b':
		body = strconv.FormatInt(int64(u), 2)
		if f.alt {
			prefix = "0b"
		}
	case 'o':
		body = strconv.FormatInt(int64(u), 8)
		if f.alt {
			prefix = "0o"
		}
	case 'x':
		body = strconv.FormatInt(int64(u), 16)
		if f.alt {
			prefix = "0x"
		}
	case 'X':
		body = strings.ToUpper(strconv.FormatInt(int64(u), 16))
		if f.alt {
			prefix = "0X"
		}
	case 'c':
		return f.pad(string(rune(u)))
	default: // 'd' or 0
		body = strconv.FormatInt(int64(u), 10)
		if f.grouping != 0 {
			body = groupDigits(body, f.grouping, 3)
		}
	}
	return f.padNumeric(f.signStr(neg), prefix+body)
}

func (f formatSpec) formatFloat(v any) string {
	x, ok := zincpyNum(v)
	if !ok {
		if n, ok := zincpyIntish(v); ok {
			x = float64(n)
		}
	}
	neg := math.Signbit(x)
	ax := math.Abs(x)
	prec := f.precision
	var body string
	switch f.typ {
	case 'e', 'E':
		if prec < 0 {
			prec = 6
		}
		body = strconv.FormatFloat(ax, f.typ, prec, 64)
	case 'g', 'G':
		if prec < 0 {
			prec = 6
		}
		if prec == 0 {
			prec = 1
		}
		body = strconv.FormatFloat(ax, f.typ, prec, 64)
	case '%':
		if prec < 0 {
			prec = 6
		}
		body = strconv.FormatFloat(ax*100, 'f', prec, 64) + "%"
	default: // 'f', 'F', or 0
		if prec < 0 {
			prec = 6
		}
		body = strconv.FormatFloat(ax, 'f', prec, 64)
	}
	if f.grouping != 0 {
		body = groupFloat(body, f.grouping)
	}
	return f.padNumeric(f.signStr(neg), body)
}

// groupDigits inserts the grouping separator every n digits from the right.
func groupDigits(s string, sep byte, n int) string {
	if len(s) <= n {
		return s
	}
	var b strings.Builder
	pre := len(s) % n
	if pre > 0 {
		b.WriteString(s[:pre])
	}
	for i := pre; i < len(s); i += n {
		if b.Len() > 0 {
			b.WriteByte(sep)
		}
		b.WriteString(s[i : i+n])
	}
	return b.String()
}

// groupFloat applies digit grouping to the integer part of a formatted float,
// leaving the fractional part (and any exponent) untouched.
func groupFloat(s string, sep byte) string {
	dot := strings.IndexByte(s, '.')
	if dot < 0 {
		return groupDigits(s, sep, 3)
	}
	return groupDigits(s[:dot], sep, 3) + s[dot:]
}

// zincpyPrintN mirrors Python's print() for any number of arguments: each is
// str()-formatted and joined with a single space, newline-terminated. This is
// Python's default sep=' ', end='\n'.
func zincpyPrintN(vs ...any) {
	parts := make([]string, len(vs))
	for i, v := range vs {
		parts[i] = zincpyStr(v)
	}
	fmt.Println(strings.Join(parts, " "))
}

// zincpyPrintSep mirrors print(*vs, sep=sep, end=end): each value is
// str()-formatted, joined by sep, then end is written (end IS the terminator,
// so no implicit newline). The front-end passes sep/end first, defaulting them
// to " " and "\n" when the call omits them.
func zincpyPrintSep(sep, end string, vs ...any) {
	parts := make([]string, len(vs))
	for i, v := range vs {
		parts[i] = zincpyStr(v)
	}
	fmt.Print(strings.Join(parts, sep) + end)
}

// zincpyUpper / zincpyLower mirror str.upper()/str.lower(). (ASCII-equivalent
// to Python; full Unicode case folding is a known gap.)
func zincpyUpper(s string) string { return strings.ToUpper(s) }
func zincpyLower(s string) string { return strings.ToLower(s) }

// zincpyStrip is str.strip(): no argument trims surrounding whitespace; an
// argument trims any of the given characters from both ends.
func zincpyStrip(s string, chars ...string) string {
	if len(chars) == 0 {
		return strings.TrimSpace(s)
	}
	return strings.Trim(s, chars[0])
}

// zincpyReplace is str.replace(old, new): replaces every occurrence (Python's
// default count of -1).
func zincpyReplace(s, old, replacement string) string {
	return strings.ReplaceAll(s, old, replacement)
}

// zincpyLstrip / zincpyRstrip are str.lstrip()/str.rstrip(): no argument trims
// surrounding whitespace from one side; an argument trims any of the given
// characters from that side.
func zincpyLstrip(s string, chars ...string) string {
	if len(chars) == 0 {
		return strings.TrimLeft(s, " \t\n\r\v\f")
	}
	return strings.TrimLeft(s, chars[0])
}

func zincpyRstrip(s string, chars ...string) string {
	if len(chars) == 0 {
		return strings.TrimRight(s, " \t\n\r\v\f")
	}
	return strings.TrimRight(s, chars[0])
}

// zincpyTitle is str.title(): the first letter of each run of letters is
// uppercased and the rest lowercased, where any non-letter (digit, space,
// punctuation) ends a word — matching CPython's quirky boundaries
// ("they're".title() == "They'Re").
func zincpyTitle(s string) string {
	var b strings.Builder
	prevCased := false
	for _, r := range s {
		if unicode.IsLetter(r) {
			if prevCased {
				b.WriteRune(unicode.ToLower(r))
			} else {
				b.WriteRune(unicode.ToTitle(r))
			}
			prevCased = true
		} else {
			b.WriteRune(r)
			prevCased = false
		}
	}
	return b.String()
}

// zincpyCapitalize is str.capitalize(): first character uppercased, the rest
// lowercased.
func zincpyCapitalize(s string) string {
	if s == "" {
		return s
	}
	r, size := utf8.DecodeRuneInString(s)
	return string(unicode.ToTitle(r)) + strings.ToLower(s[size:])
}

// padFill returns the single padding rune for ljust/rjust/center (default
// space); Python requires the fill to be exactly one character.
func padFill(fill []string) rune {
	if len(fill) > 0 && fill[0] != "" {
		r, _ := utf8.DecodeRuneInString(fill[0])
		return r
	}
	return ' '
}

// zincpyRjust / zincpyLjust are str.rjust()/str.ljust(): pad to width characters
// (counted as Python code points) with fill on the left/right; returns s
// unchanged when already at least width wide.
func zincpyRjust(s string, width int, fill ...string) string {
	if pad := width - utf8.RuneCountInString(s); pad > 0 {
		return strings.Repeat(string(padFill(fill)), pad) + s
	}
	return s
}

func zincpyLjust(s string, width int, fill ...string) string {
	if pad := width - utf8.RuneCountInString(s); pad > 0 {
		return s + strings.Repeat(string(padFill(fill)), pad)
	}
	return s
}

// zincpyCenter is str.center(): center s in a field of width characters. The
// extra padding (odd margin) goes on the right, matching CPython's
// left = marg/2 + (marg & width & 1) rule.
func zincpyCenter(s string, width int, fill ...string) string {
	marg := width - utf8.RuneCountInString(s)
	if marg <= 0 {
		return s
	}
	left := marg/2 + (marg & width & 1)
	f := string(padFill(fill))
	return strings.Repeat(f, left) + s + strings.Repeat(f, marg-left)
}

// zincpyStartswith / zincpyEndswith mirror str.startswith()/str.endswith().
func zincpyStartswith(s, prefix string) bool { return strings.HasPrefix(s, prefix) }
func zincpyEndswith(s, suffix string) bool   { return strings.HasSuffix(s, suffix) }

// zincpyFind is str.find(): the byte index of the first occurrence, or -1.
func zincpyFind(s, sub string) int { return strings.Index(s, sub) }

// zincpyCount is str.count(): the number of non-overlapping occurrences.
func zincpyCount(s, sub string) int { return strings.Count(s, sub) }

// str predicate methods. Each mirrors CPython's str.isX(): the empty string is
// always False, and the test runs over every Unicode code point. (CPython's
// isdigit/isnumeric distinguish Numeric_Type subtleties that unicode.IsDigit/
// IsNumber approximate; identical for ASCII and the common cases.)
func zincpyIsalpha(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if !unicode.IsLetter(r) {
			return false
		}
	}
	return true
}

func zincpyIsdigit(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}

func zincpyIsalnum(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if !(unicode.IsLetter(r) || unicode.IsDigit(r) || unicode.IsNumber(r)) {
			return false
		}
	}
	return true
}

func zincpyIsspace(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if !unicode.IsSpace(r) {
			return false
		}
	}
	return true
}

// isupper/islower: True iff there is at least one cased character and every
// cased character is of that case (a titlecased rune counts as neither).
func zincpyIsupper(s string) bool {
	cased := false
	for _, r := range s {
		if unicode.IsLower(r) || unicode.IsTitle(r) {
			return false
		}
		if unicode.IsUpper(r) {
			cased = true
		}
	}
	return cased
}

func zincpyIslower(s string) bool {
	cased := false
	for _, r := range s {
		if unicode.IsUpper(r) || unicode.IsTitle(r) {
			return false
		}
		if unicode.IsLower(r) {
			cased = true
		}
	}
	return cased
}

// istitle: uppercase/titlecase runes may only follow an uncased rune; lowercase
// runes only a cased one. False if there are no cased characters.
func zincpyIstitle(s string) bool {
	cased, prevCased := false, false
	for _, r := range s {
		switch {
		case unicode.IsUpper(r) || unicode.IsTitle(r):
			if prevCased {
				return false
			}
			prevCased, cased = true, true
		case unicode.IsLower(r):
			if !prevCased {
				return false
			}
			prevCased, cased = true, true
		default:
			prevCased = false
		}
	}
	return cased
}

// zincpySplit is str.split(): with no separator it splits on runs of
// whitespace and drops empty fields (Python's default); with a separator it
// splits on each occurrence.
func zincpySplit(s string, args ...any) []string {
	if len(args) == 0 {
		return strings.Fields(s)
	}
	sep, _ := args[0].(string)
	if len(args) >= 2 {
		// str.split(sep, maxsplit): at most maxsplit splits → maxsplit+1 fields.
		if n, ok := zincpyIntish(args[1]); ok && n >= 0 {
			return strings.SplitN(s, sep, n+1)
		}
	}
	return strings.Split(s, sep)
}

// zincpyJoin is sep.join(items): the receiver string joins the elements.
func zincpyJoin(sep string, items []string) string {
	return strings.Join(items, sep)
}

// zincpyRangeList materializes range(...) used in value position into a []int,
// matching Python's range(stop) / range(start, stop) / range(start, stop, step).
// A zero step raises ValueError, as in CPython; an empty range yields [].
func zincpyRangeList(args ...int) []int {
	start, stop, step := 0, 0, 1
	switch len(args) {
	case 1:
		stop = args[0]
	case 2:
		start, stop = args[0], args[1]
	case 3:
		start, stop, step = args[0], args[1], args[2]
	}
	if step == 0 {
		panic(zincpyExc{"ValueError", "range() arg 3 must not be zero"})
	}
	out := []int{}
	if step > 0 {
		for i := start; i < stop; i += step {
			out = append(out, i)
		}
	} else {
		for i := start; i > stop; i += step {
			out = append(out, i)
		}
	}
	return out
}

// zincpyChars yields each character of s as a length-1 string, matching how
// Python iterates a str (length-1 strings, not Go runes). Iterating by rune
// makes a multi-byte code point a single character, as in Python.
func zincpyChars(s string) []string {
	out := make([]string, 0, len(s))
	for _, r := range s {
		out = append(out, string(r))
	}
	return out
}

// --- list methods ------------------------------------------------------------
//
// Python list mutators return None and mutate in place; the front-end lowers
// xs.m(...) to xs = zincpyM(xs, ...), mirroring the existing .append rewrite (so
// they share its aliasing caveat: a separate name bound to the same list does
// not observe the change). index/count are pure and lower to a value.

// zincpySort / zincpySortRev implement list.sort() and list.sort(reverse=True).
// Ordering is by the elements' natural less-than (no key= support); equal
// elements are indistinguishable, so the unstable sort.Slice matches Python.
func zincpySort[T cmp.Ordered](xs []T) []T {
	sort.Slice(xs, func(i, j int) bool { return xs[i] < xs[j] })
	return xs
}

func zincpySortRev[T cmp.Ordered](xs []T) []T {
	sort.Slice(xs, func(i, j int) bool { return xs[i] > xs[j] })
	return xs
}

// zincpyReverseList implements list.reverse() (in place).
func zincpyReverseList[T any](xs []T) []T {
	for i, j := 0, len(xs)-1; i < j; i, j = i+1, j-1 {
		xs[i], xs[j] = xs[j], xs[i]
	}
	return xs
}

// zincpyInsert implements list.insert(i, v): a negative index counts from the
// end (clamped to 0), an index past the end appends.
func zincpyInsert[T any](xs []T, i int, v T) []T {
	if i < 0 {
		if i += len(xs); i < 0 {
			i = 0
		}
	}
	if i > len(xs) {
		i = len(xs)
	}
	var zero T
	xs = append(xs, zero)
	copy(xs[i+1:], xs[i:])
	xs[i] = v
	return xs
}

// zincpyListIndex implements list.index(v): the first matching index, or a
// ValueError with CPython's fixed message when absent.
func zincpyListIndex[T comparable](xs []T, v T) int {
	for i, x := range xs {
		if x == v {
			return i
		}
	}
	panic(zincpyExc{"ValueError", "list.index(x): x not in list"})
}

// zincpyListCount implements list.count(v).
func zincpyListCount[T comparable](xs []T, v T) int {
	n := 0
	for _, x := range xs {
		if x == v {
			n++
		}
	}
	return n
}

// list.pop([i]): the front-end emits the value-read (zincpyPopVal*) then the
// slice write-back (zincpyPopDrop*) as two statements. The Val helper runs first
// and validates, so the paired Drop helper can assume a valid, non-empty slice.
func zincpyPopVal[T any](xs []T) T {
	if len(xs) == 0 {
		panic(zincpyExc{"IndexError", "pop from empty list"})
	}
	return xs[len(xs)-1]
}

func zincpyPopDrop[T any](xs []T) []T {
	return xs[:len(xs)-1]
}

func zincpyPopValAt[T any](xs []T, i int) T {
	n := len(xs)
	if i < 0 {
		i += n
	}
	if i < 0 || i >= n {
		panic(zincpyExc{"IndexError", "pop index out of range"})
	}
	return xs[i]
}

func zincpyPopDropAt[T any](xs []T, i int) []T {
	if i < 0 {
		i += len(xs)
	}
	return append(xs[:i], xs[i+1:]...)
}

// zincpyStrMethod dispatches a str method called on a DYNAMIC receiver (an
// unannotated / duck-typed value the front-end could not lower to the typed
// helper). The receiver must be a string at run time — Python raises
// AttributeError otherwise — and string arguments are likewise asserted. The
// result is boxed (any) since the receiver's type was not known statically.
func zincpyStrMethod(recv any, method string, args ...any) any {
	s, ok := recv.(string)
	if !ok {
		panic(zincpyExc{"AttributeError", zincpyTypeName(recv) + " object has no attribute " + zincpyRepr(method)})
	}
	argStr := func(i int) string {
		a, ok := args[i].(string)
		if !ok {
			panic(zincpyExc{"TypeError", method + "() argument must be str, not " + zincpyTypeName(args[i])})
		}
		return a
	}
	argInt := func(i int) int {
		n, ok := zincpyIntish(args[i])
		if !ok {
			panic(zincpyExc{"TypeError", method + "() argument must be int, not " + zincpyTypeName(args[i])})
		}
		return n
	}
	optFill := func(i int) []string {
		if len(args) > i {
			return []string{argStr(i)}
		}
		return nil
	}
	switch method {
	case "upper":
		return zincpyUpper(s)
	case "lower":
		return zincpyLower(s)
	case "title":
		return zincpyTitle(s)
	case "capitalize":
		return zincpyCapitalize(s)
	case "strip":
		if len(args) == 0 {
			return zincpyStrip(s)
		}
		return zincpyStrip(s, argStr(0))
	case "lstrip":
		if len(args) == 0 {
			return zincpyLstrip(s)
		}
		return zincpyLstrip(s, argStr(0))
	case "rstrip":
		if len(args) == 0 {
			return zincpyRstrip(s)
		}
		return zincpyRstrip(s, argStr(0))
	case "ljust":
		return zincpyLjust(s, argInt(0), optFill(1)...)
	case "rjust":
		return zincpyRjust(s, argInt(0), optFill(1)...)
	case "center":
		return zincpyCenter(s, argInt(0), optFill(1)...)
	case "replace":
		return zincpyReplace(s, argStr(0), argStr(1))
	case "startswith":
		return zincpyStartswith(s, argStr(0))
	case "endswith":
		return zincpyEndswith(s, argStr(0))
	case "find":
		return zincpyFind(s, argStr(0))
	case "count":
		return zincpyCount(s, argStr(0))
	case "isalpha":
		return zincpyIsalpha(s)
	case "isdigit":
		return zincpyIsdigit(s)
	case "isalnum":
		return zincpyIsalnum(s)
	case "isspace":
		return zincpyIsspace(s)
	case "isupper":
		return zincpyIsupper(s)
	case "islower":
		return zincpyIslower(s)
	case "istitle":
		return zincpyIstitle(s)
	case "split":
		if len(args) == 0 {
			return zincpySplit(s)
		}
		if len(args) >= 2 {
			return zincpySplit(s, argStr(0), argInt(1))
		}
		return zincpySplit(s, argStr(0))
	case "join":
		items := zincpySeq(args[0])
		strs := make([]string, len(items))
		for i, item := range items {
			si, ok := item.(string)
			if !ok {
				panic(zincpyExc{"TypeError", "sequence item " + strconv.Itoa(i) + ": expected str instance, " + zincpyTypeName(item) + " found"})
			}
			strs[i] = si
		}
		return zincpyJoin(s, strs)
	}
	panic(zincpyExc{"AttributeError", "str object has no attribute " + zincpyRepr(method)})
}

// --- dynamic-value operations ------------------------------------------------
//
// These dispatch on the boxed runtime type of a dynamic value (an FFI result
// or something derived from one). The front-end routes index/iterate/len and
// numeric coercion on a dynamic value here instead of emitting native Go,
// which cannot operate on an interface{}.

// zincpyGetItem is Python subscription d[k] on a dynamic value: sequence
// indexing (with negative-index wraparound) for lists and strings, key lookup
// for dicts.
func zincpyGetItem(container, key any) any {
	switch c := container.(type) {
	case []any:
		i := key.(int)
		if i < 0 {
			i += len(c)
		}
		if i < 0 || i >= len(c) {
			panic(zincpyExc{"IndexError", "list index out of range"})
		}
		return c[i]
	case zincpyTuple:
		i := key.(int)
		if i < 0 {
			i += len(c.items)
		}
		if i < 0 || i >= len(c.items) {
			panic(zincpyExc{"IndexError", "tuple index out of range"})
		}
		return c.items[i]
	case *zincpyDict:
		if !c.Has(key) {
			panic(zincpyExc{"KeyError", zincpyRepr(key)})
		}
		return c.Get(key)
	case string:
		rs := []rune(c)
		i := key.(int)
		if i < 0 {
			i += len(rs)
		}
		if i < 0 || i >= len(rs) {
			panic(zincpyExc{"IndexError", "string index out of range"})
		}
		return string(rs[i])
	}
	// A typed slice (e.g. []int) reaching here was boxed into a dynamic value
	// (passed to an unannotated param); index it reflectively.
	if rv := reflect.ValueOf(container); rv.IsValid() && rv.Kind() == reflect.Slice {
		i := key.(int)
		if i < 0 {
			i += rv.Len()
		}
		if i < 0 || i >= rv.Len() {
			panic(zincpyExc{"IndexError", "list index out of range"})
		}
		return rv.Index(i).Interface()
	}
	panic(zincpyExc{"TypeError", "object is not subscriptable"})
}

// zincpyIter yields the elements to range over for a for-in loop on a dynamic
// value: list elements, dict keys (insertion order), or string characters.
func zincpyIter(container any) []any {
	switch c := container.(type) {
	case []any:
		return c
	case zincpyTuple:
		return c.items
	case *zincpyDict:
		return c.Keys()
	case string:
		rs := []rune(c)
		out := make([]any, len(rs))
		for i, r := range rs {
			out[i] = string(r)
		}
		return out
	}
	// Sets and arbitrary typed slices (boxed into a dynamic value) — materialize
	// reflectively. zincpySeq raises the same TypeError for non-iterables.
	return zincpySeq(container)
}

// zincpyLen is len() on a dynamic value.
func zincpyLen(container any) int {
	switch c := container.(type) {
	case []any:
		return len(c)
	case zincpyTuple:
		return len(c.items)
	case *zincpyDict:
		return c.Len()
	case string:
		return len([]rune(c))
	case *zincpySet:
		return c.Len()
	}
	// A typed slice/map/array boxed into a dynamic value.
	if rv := reflect.ValueOf(container); rv.IsValid() {
		switch rv.Kind() {
		case reflect.Slice, reflect.Map, reflect.Array:
			return rv.Len()
		}
	}
	panic(zincpyExc{"TypeError", "object has no len()"})
}

// zincpyToFloat is Python float() on a dynamic value.
func zincpyToFloat(v any) float64 {
	switch x := v.(type) {
	case float64:
		return x
	case int:
		return float64(x)
	case bool:
		if x {
			return 1
		}
		return 0
	case string:
		f, err := strconv.ParseFloat(strings.TrimSpace(x), 64)
		if err != nil {
			panic(zincpyExc{"ValueError", "could not convert string to float: " + zincpyRepr(x)})
		}
		return f
	}
	panic(zincpyExc{"TypeError", "float() argument must be a string or a number"})
}

// zincpyToInt is Python int() on a dynamic value; float truncates toward zero.
func zincpyToInt(v any) int {
	switch x := v.(type) {
	case int:
		return x
	case float64:
		return int(x)
	case bool:
		if x {
			return 1
		}
		return 0
	case string:
		n, err := strconv.Atoi(strings.TrimSpace(x))
		if err != nil {
			panic(zincpyExc{"ValueError", "invalid literal for int() with base 10: " + zincpyRepr(x)})
		}
		return n
	}
	panic(zincpyExc{"TypeError", "int() argument must be a string or a number"})
}

// zincpyToBool coerces a dynamic value to a Go bool for a bool-typed return: a
// genuine bool passes through; anything else falls back to Python truthiness.
func zincpyToBool(v any) bool {
	if b, ok := v.(bool); ok {
		return b
	}
	return zincpyTruthy(v)
}

// --- dynamic binary operators ------------------------------------------------
//
// When an operand of a binary op is dynamic, the front-end can't pick a Go
// operator statically, so it emits one of these. They reproduce Python's
// operator overloading: numeric tower (int stays int; any float widens),
// str/list/tuple concatenation, and sequence repetition.

func zincpyTypeName(v any) string {
	switch v.(type) {
	case int:
		return "'int'"
	case float64:
		return "'float'"
	case string:
		return "'str'"
	case bool:
		return "'bool'"
	case []any:
		return "'list'"
	case *zincpyDict:
		return "'dict'"
	case zincpyTuple:
		return "'tuple'"
	case nil:
		return "'NoneType'"
	}
	return "'object'"
}

// zincpyIntish reports an integer value for int/bool (Python treats bool as a
// subclass of int, so True + 1 == 2).
func zincpyIntish(v any) (int, bool) {
	switch x := v.(type) {
	case int:
		return x, true
	case bool:
		if x {
			return 1, true
		}
		return 0, true
	}
	return 0, false
}

func zincpyNum(v any) (float64, bool) {
	switch x := v.(type) {
	case float64:
		return x, true
	case int:
		return float64(x), true
	case bool:
		if x {
			return 1, true
		}
		return 0, true
	}
	return 0, false
}

// zincpyIdx normalizes a (possibly negative) sequence index against the
// length, matching Python: xs[-1] is the last element. Positive indices pass
// through unchanged.
func zincpyIdx(i, n int) int {
	if i < 0 {
		return i + n
	}
	return i
}

// zincpyNeg is unary minus on a dynamic value.
func zincpyNeg(v any) any {
	switch x := v.(type) {
	case int:
		return -x
	case float64:
		return -x
	case bool:
		if x {
			return -1
		}
		return 0
	}
	panic(zincpyExc{"TypeError", "bad operand type for unary -: " + zincpyTypeName(v)})
}

func zincpyAdd(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return ai + bi
		}
	}
	if af, ok := zincpyNum(a); ok {
		if bf, ok := zincpyNum(b); ok {
			return af + bf
		}
	}
	if as, ok := a.(string); ok {
		if bs, ok := b.(string); ok {
			return as + bs
		}
	}
	if al, ok := a.([]any); ok {
		if bl, ok := b.([]any); ok {
			r := make([]any, 0, len(al)+len(bl))
			return append(append(r, al...), bl...)
		}
	}
	if at, ok := a.(zincpyTuple); ok {
		if bt, ok := b.(zincpyTuple); ok {
			it := make([]any, 0, len(at.items)+len(bt.items))
			return zincpyTuple{items: append(append(it, at.items...), bt.items...)}
		}
	}
	// Typed slices (e.g. []int) boxed into dynamic values concatenate like
	// lists, producing a []any (matching Python list +).
	if ra, rb := reflect.ValueOf(a), reflect.ValueOf(b); ra.IsValid() && rb.IsValid() &&
		ra.Kind() == reflect.Slice && rb.Kind() == reflect.Slice {
		r := make([]any, 0, ra.Len()+rb.Len())
		for i := 0; i < ra.Len(); i++ {
			r = append(r, ra.Index(i).Interface())
		}
		for i := 0; i < rb.Len(); i++ {
			r = append(r, rb.Index(i).Interface())
		}
		return r
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for +: " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
}

func zincpySub(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return ai - bi
		}
	}
	if af, ok := zincpyNum(a); ok {
		if bf, ok := zincpyNum(b); ok {
			return af - bf
		}
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for -: " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
}

// zincpyParseInt / zincpyParseFloat are int(str) / float(str): parse the string
// the Python way, raising ValueError on a malformed literal. int() ignores
// surrounding whitespace.
func zincpyParseInt(s string) int {
	n, err := strconv.Atoi(strings.TrimSpace(s))
	if err != nil {
		panic(zincpyExc{"ValueError", "invalid literal for int() with base 10: " + zincpyRepr(s)})
	}
	return n
}

func zincpyParseFloat(s string) float64 {
	f, err := strconv.ParseFloat(strings.TrimSpace(s), 64)
	if err != nil {
		panic(zincpyExc{"ValueError", "could not convert string to float: " + zincpyRepr(s)})
	}
	return f
}

// zincpyRound is round(x) → int using banker's rounding (round half to even),
// matching Python (round(2.5) == 2, round(3.5) == 4).
func zincpyRound(x any) int {
	f, _ := zincpyNum(x)
	return int(math.RoundToEven(f))
}

// zincpyRoundN is round(x, ndigits) → float, also banker's rounding at the
// given decimal place.
func zincpyRoundN(x any, ndigits any) float64 {
	f, _ := zincpyNum(x)
	n, _ := zincpyIntish(ndigits)
	scale := math.Pow(10, float64(n))
	return math.RoundToEven(f*scale) / scale
}

// zincpyPow is the power operator: int to a non-negative int power stays int
// (exact), anything else (float operand, or a negative exponent) is float —
// matching CPython.
func zincpyPow(a, b any) any {
	if ai, aok := zincpyIntish(a); aok {
		if bi, bok := zincpyIntish(b); bok && bi >= 0 {
			result := 1
			for i := 0; i < bi; i++ {
				result *= ai
			}
			return result
		}
	}
	af, ao := zincpyNum(a)
	bf, bo := zincpyNum(b)
	if ao && bo {
		return math.Pow(af, bf)
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for ** : " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
}

func zincpyMul(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return ai * bi
		}
	}
	if af, ok := zincpyNum(a); ok {
		if bf, ok := zincpyNum(b); ok {
			return af * bf
		}
	}
	// sequence repetition: str*int and list*int (either order)
	if s, n, ok := zincpyStrRepeat(a, b); ok {
		return strings.Repeat(s, n)
	}
	if lst, n, ok := zincpyListRepeat(a, b); ok {
		out := make([]any, 0, len(lst)*n)
		for i := 0; i < n; i++ {
			out = append(out, lst...)
		}
		return out
	}
	panic(zincpyExc{"TypeError", "can't multiply " + zincpyTypeName(a) + " by " + zincpyTypeName(b)})
}

func zincpyStrRepeat(a, b any) (string, int, bool) {
	if s, ok := a.(string); ok {
		if n, ok := zincpyIntish(b); ok {
			return s, n, true
		}
	}
	if s, ok := b.(string); ok {
		if n, ok := zincpyIntish(a); ok {
			return s, n, true
		}
	}
	return "", 0, false
}

func zincpyListRepeat(a, b any) ([]any, int, bool) {
	// A list operand may be a typed slice ([]int from a literal) as well as
	// []any, so detect any slice kind via reflection and materialize it.
	if isGoSlice(a) {
		if n, ok := zincpyIntish(b); ok {
			return zincpySeq(a), n, true
		}
	}
	if isGoSlice(b) {
		if n, ok := zincpyIntish(a); ok {
			return zincpySeq(b), n, true
		}
	}
	return nil, 0, false
}

// isGoSlice reports whether v is any Go slice (any element type).
func isGoSlice(v any) bool {
	return v != nil && reflect.TypeOf(v).Kind() == reflect.Slice
}

// zincpyTrueDiv is Python / on dynamic operands: always float, /0 raises.
func zincpyTrueDiv(a, b any) float64 {
	af, ao := zincpyNum(a)
	bf, bo := zincpyNum(b)
	if !ao || !bo {
		panic(zincpyExc{"TypeError", "unsupported operand type(s) for /: " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
	}
	if bf == 0 {
		panic(zincpyExc{"ZeroDivisionError", "division by zero"})
	}
	return af / bf
}

// zincpyFloorDivDyn / zincpyModDyn are Python // and % on dynamic operands:
// int-int stays int with floor/sign-of-divisor semantics; float operands use
// math.Floor.
func zincpyFloorDivDyn(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return zincpyFloorDiv(ai, bi)
		}
	}
	af, ao := zincpyNum(a)
	bf, bo := zincpyNum(b)
	if ao && bo {
		if bf == 0 {
			panic(zincpyExc{"ZeroDivisionError", "float floor division by zero"})
		}
		return math.Floor(af / bf)
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for //"})
}

func zincpyModDyn(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return zincpyMod(ai, bi)
		}
	}
	af, ao := zincpyNum(a)
	bf, bo := zincpyNum(b)
	if ao && bo {
		if bf == 0 {
			panic(zincpyExc{"ZeroDivisionError", "float modulo"})
		}
		m := math.Mod(af, bf)
		if m != 0 && (m < 0) != (bf < 0) {
			m += bf
		}
		return m
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for %"})
}

// zincpyEq / zincpyNe / ordering compare dynamic operands the Python way:
// numbers compare across int/float, strings lexically.
func zincpyEq(a, b any) bool {
	if af, ao := zincpyNum(a); ao {
		if bf, bo := zincpyNum(b); bo {
			return af == bf
		}
	}
	return reflect.DeepEqual(a, b)
}

func zincpyNe(a, b any) bool { return !zincpyEq(a, b) }

func zincpyCmp(a, b any) int {
	if af, ao := zincpyNum(a); ao {
		if bf, bo := zincpyNum(b); bo {
			switch {
			case af < bf:
				return -1
			case af > bf:
				return 1
			default:
				return 0
			}
		}
	}
	if as, ok := a.(string); ok {
		if bs, ok := b.(string); ok {
			return strings.Compare(as, bs)
		}
	}
	// Tuples and lists compare lexicographically (element by element, shorter
	// is less when one is a prefix of the other) — Python's behavior, and what
	// sorted(d.items()) relies on.
	if as, ok := zincpySeqItems(a); ok {
		if bs, ok := zincpySeqItems(b); ok {
			return zincpySeqCmp(as, bs)
		}
	}
	panic(zincpyExc{"TypeError", "'<' not supported between instances of " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
}

// zincpySeqItems returns the element slice of a tuple or list value (and true),
// or nil/false for anything else.
func zincpySeqItems(v any) ([]any, bool) {
	switch x := v.(type) {
	case zincpyTuple:
		return x.items, true
	case *zincpyTuple:
		return x.items, true
	case []any:
		return x, true
	}
	return nil, false
}

// zincpySeqCmp compares two sequences lexicographically using zincpyCmp on
// elements, mirroring Python's tuple/list ordering.
func zincpySeqCmp(a, b []any) int {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if c := zincpyCmp(a[i], b[i]); c != 0 {
			return c
		}
	}
	switch {
	case len(a) < len(b):
		return -1
	case len(a) > len(b):
		return 1
	default:
		return 0
	}
}

func zincpyLt(a, b any) bool { return zincpyCmp(a, b) < 0 }
func zincpyGt(a, b any) bool { return zincpyCmp(a, b) > 0 }
func zincpyLe(a, b any) bool { return zincpyCmp(a, b) <= 0 }
func zincpyGe(a, b any) bool { return zincpyCmp(a, b) >= 0 }

// zincpyTruthy implements Python truthiness for a condition value: None, zero
// numbers, empty string, and empty containers are falsy; everything else
// (including any object) is truthy.
func zincpyTruthy(v any) bool {
	switch x := v.(type) {
	case nil:
		return false
	case bool:
		return x
	case int:
		return x != 0
	case float64:
		return x != 0
	case string:
		return x != ""
	case []any:
		return len(x) != 0
	case zincpyTuple:
		return len(x.items) != 0
	case *zincpyDict:
		return x.Len() != 0
	case *zincpySet:
		return x.Len() != 0
	}
	rv := reflect.ValueOf(v)
	switch rv.Kind() {
	case reflect.Slice, reflect.Map, reflect.Array:
		return rv.Len() != 0
	}
	return true
}

// --- builtins over sequences -------------------------------------------------
//
// min/max/sum/sorted accept any slice kind (the front-end's homogeneous list
// literals become concrete Go slices), so they reflect over the elements and
// return boxed (dynamic) results.

func zincpySeq(xs any) []any {
	rv := reflect.ValueOf(xs)
	if !rv.IsValid() || rv.Kind() != reflect.Slice {
		switch v := xs.(type) {
		case string:
			rs := []rune(v)
			out := make([]any, len(rs))
			for i, r := range rs {
				out[i] = string(r)
			}
			return out
		case zincpyTuple:
			return v.items
		case *zincpyDict:
			return v.Keys()
		case *zincpySet:
			return v.Keys()
		}
		panic(zincpyExc{"TypeError", "object is not iterable"})
	}
	out := make([]any, rv.Len())
	for i := range out {
		out[i] = rv.Index(i).Interface()
	}
	return out
}

func zincpyMin(xs any) any {
	s := zincpySeq(xs)
	if len(s) == 0 {
		panic(zincpyExc{"ValueError", "min() arg is an empty sequence"})
	}
	best := s[0]
	for _, v := range s[1:] {
		if zincpyCmp(v, best) < 0 {
			best = v
		}
	}
	return best
}

func zincpyMax(xs any) any {
	s := zincpySeq(xs)
	if len(s) == 0 {
		panic(zincpyExc{"ValueError", "max() arg is an empty sequence"})
	}
	best := s[0]
	for _, v := range s[1:] {
		if zincpyCmp(v, best) > 0 {
			best = v
		}
	}
	return best
}

// zincpySum mirrors Python sum(): result is int unless any element is float.
func zincpySum(xs any) any {
	s := zincpySeq(xs)
	isum, fsum, isFloat := 0, 0.0, false
	for _, v := range s {
		switch x := v.(type) {
		case int:
			isum += x
			fsum += float64(x)
		case bool:
			if x {
				isum++
				fsum++
			}
		case float64:
			isFloat = true
			fsum += x
		default:
			panic(zincpyExc{"TypeError", "unsupported operand type for sum(): " + zincpyTypeName(v)})
		}
	}
	if isFloat {
		return fsum
	}
	return isum
}

func zincpySorted(xs any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	copy(out, s)
	sort.SliceStable(out, func(i, j int) bool { return zincpyCmp(out[i], out[j]) < 0 })
	return out
}

// zincpySortedKey is sorted(xs, key=f): order by f(element).
func zincpySortedKey(xs any, key func(any) any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	copy(out, s)
	sort.SliceStable(out, func(i, j int) bool { return zincpyCmp(key(out[i]), key(out[j])) < 0 })
	return out
}

// zincpyList is list(x): materialize any iterable into a new []any.
func zincpyList(xs any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	copy(out, s)
	return out
}

// zincpyMap is map(f, xs): f applied to each element.
func zincpyMap(f func(any) any, xs any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	for i, v := range s {
		out[i] = f(v)
	}
	return out
}

// zincpyFilter is filter(f, xs): elements where f(element) is truthy.
func zincpyFilter(f func(any) any, xs any) []any {
	var out []any
	for _, v := range zincpySeq(xs) {
		if zincpyTruthy(f(v)) {
			out = append(out, v)
		}
	}
	return out
}

// zincpySlice implements Python slicing seq[start:stop:step] on a list, string,
// or tuple. start/stop/step are int or nil (omitted). Negative indices and
// negative step are handled per CPython; the result is a new list/string/tuple.
func zincpySlice(seq, startA, stopA, stepA any) any {
	step := 1
	if stepA != nil {
		step = stepA.(int)
		if step == 0 {
			panic(zincpyExc{"ValueError", "slice step cannot be zero"})
		}
	}
	switch s := seq.(type) {
	case string:
		rs := []rune(s)
		var b strings.Builder
		for _, i := range zincpySliceIndices(len(rs), startA, stopA, step) {
			b.WriteRune(rs[i])
		}
		return b.String()
	case zincpyTuple:
		idxs := zincpySliceIndices(len(s.items), startA, stopA, step)
		out := make([]any, len(idxs))
		for k, i := range idxs {
			out[k] = s.items[i]
		}
		return zincpyTuple{items: out}
	}
	elems := zincpySeq(seq)
	idxs := zincpySliceIndices(len(elems), startA, stopA, step)
	out := make([]any, len(idxs))
	for k, i := range idxs {
		out[k] = elems[i]
	}
	return out
}

// zincpySliceIndices returns the concrete indices a slice selects, mirroring
// CPython's slice.indices(length).
func zincpySliceIndices(n int, startA, stopA any, step int) []int {
	lower, upper := 0, n
	if step < 0 {
		lower, upper = -1, n-1
	}
	clamp := func(i int) int {
		if i < lower {
			return lower
		}
		if i > upper {
			return upper
		}
		return i
	}
	var start, stop int
	if startA == nil {
		if step < 0 {
			start = upper
		} else {
			start = lower
		}
	} else {
		start = startA.(int)
		if start < 0 {
			start += n
		}
		start = clamp(start)
	}
	if stopA == nil {
		if step < 0 {
			stop = lower
		} else {
			stop = upper
		}
	} else {
		stop = stopA.(int)
		if stop < 0 {
			stop += n
		}
		stop = clamp(stop)
	}
	var idxs []int
	if step > 0 {
		for i := start; i < stop; i += step {
			idxs = append(idxs, i)
		}
	} else {
		for i := start; i > stop; i += step {
			idxs = append(idxs, i)
		}
	}
	return idxs
}

// zincpyEnumerate mirrors enumerate(xs): (index, element) 2-tuples.
// zincpyAny / zincpyAll mirror any()/all(): truthiness of the elements, with
// Python's empty-iterable conventions (any([]) is False, all([]) is True).
func zincpyAny(xs any) bool {
	for _, v := range zincpySeq(xs) {
		if zincpyTruthy(v) {
			return true
		}
	}
	return false
}

func zincpyAll(xs any) bool {
	for _, v := range zincpySeq(xs) {
		if !zincpyTruthy(v) {
			return false
		}
	}
	return true
}

func zincpyEnumerate(xs any, start ...int) []any {
	base := 0
	if len(start) > 0 {
		base = start[0]
	}
	s := zincpySeq(xs)
	out := make([]any, len(s))
	for i, v := range s {
		out[i] = zincpyTuple{items: []any{base + i, v}}
	}
	return out
}

// zincpyZip mirrors zip(a, b, ...): tuples of corresponding elements, stopping
// at the shortest input.
func zincpyZip(args ...any) []any {
	if len(args) == 0 {
		return nil
	}
	seqs := make([][]any, len(args))
	minLen := -1
	for i, a := range args {
		seqs[i] = zincpySeq(a)
		if minLen < 0 || len(seqs[i]) < minLen {
			minLen = len(seqs[i])
		}
	}
	out := make([]any, minLen)
	for i := 0; i < minLen; i++ {
		tup := make([]any, len(seqs))
		for j := range seqs {
			tup[j] = seqs[j][i]
		}
		out[i] = zincpyTuple{items: tup}
	}
	return out
}

func zincpyAbs(v any) any {
	switch x := v.(type) {
	case int:
		if x < 0 {
			return -x
		}
		return x
	case float64:
		return math.Abs(x)
	case bool:
		if x {
			return 1
		}
		return 0
	}
	panic(zincpyExc{"TypeError", "bad operand type for abs(): " + zincpyTypeName(v)})
}

// zincpyStr mirrors Python's str() for the value kinds the front-end emits.
func zincpyStr(v any) string {
	switch x := v.(type) {
	case float64:
		return zincpyFloat(x)
	case bool:
		if x {
			return "True"
		}
		return "False"
	case string:
		return x
	default:
		if s, ok := zincpySeqRepr(v); ok {
			return s
		}
		return fmt.Sprint(v)
	}
}

// zincpySeqRepr renders a Go slice the way Python repr renders a list:
// [e0, e1, ...] with each element via zincpyRepr (so strings are quoted and
// floats/bools use Python formatting). Returns ok=false for non-slices.
// str(list) and repr(list) are identical in Python, so both paths use this.
func zincpySeqRepr(v any) (string, bool) {
	rv := reflect.ValueOf(v)
	if !rv.IsValid() || rv.Kind() != reflect.Slice {
		return "", false
	}
	var b strings.Builder
	b.WriteByte('[')
	for i := 0; i < rv.Len(); i++ {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(zincpyRepr(rv.Index(i).Interface()))
	}
	b.WriteByte(']')
	return b.String(), true
}

// zincpyFloat formats a float the way CPython's repr/str does for the common
// (non-astronomical) range: shortest round-trip digits, with a decimal point
// forced for integer-valued floats (3 -> "3.0"). Scientific-notation
// threshold differences vs CPython are a known gap for very large/small
// magnitudes.
func zincpyFloat(f float64) string {
	switch {
	case math.IsNaN(f):
		return "nan"
	case math.IsInf(f, 1):
		return "inf"
	case math.IsInf(f, -1):
		return "-inf"
	}
	s := strconv.FormatFloat(f, 'g', -1, 64)
	for i := 0; i < len(s); i++ {
		if s[i] == '.' || s[i] == 'e' {
			return s
		}
	}
	return s + ".0"
}

// zincpyDiv is Python true division: always float, and division by zero raises
// ZeroDivisionError (Go float division would yield +Inf instead).
func zincpyDiv(a, b float64) float64 {
	if b == 0 {
		panic(zincpyExc{"ZeroDivisionError", "division by zero"})
	}
	return a / b
}

// zincpyFloorDiv is Python's // on ints: floor toward negative infinity.
// Go's / truncates toward zero, so the two differ when the operands have
// opposite signs and the division is inexact. Division by zero raises
// ZeroDivisionError (matching CPython, not a Go runtime panic).
func zincpyFloorDiv(a, b int) int {
	if b == 0 {
		panic(zincpyExc{"ZeroDivisionError", "integer division or modulo by zero"})
	}
	q := a / b
	if (a%b != 0) && ((a < 0) != (b < 0)) {
		q--
	}
	return q
}

// zincpyMod is Python's % on ints: the result takes the sign of the divisor.
// Go's % takes the sign of the dividend, so e.g. -7 % 3 is -1 in Go but 2 in
// Python.
func zincpyMod(a, b int) int {
	if b == 0 {
		panic(zincpyExc{"ZeroDivisionError", "integer division or modulo by zero"})
	}
	return ((a % b) + b) % b
}

// zincpyDict is an insertion-ordered map — Python dict semantics. Go's
// built-in map randomizes iteration order, so iteration/keys/values/printing
// would diverge from CPython without tracking insertion order explicitly.
// Keys and values are boxed (any); the front-end inserts type assertions on
// Get where the value type is known.
type zincpyDict struct {
	keys []any
	vals map[any]any
}

func zincpyNewDict() *zincpyDict {
	return &zincpyDict{vals: map[any]any{}}
}

func (d *zincpyDict) Set(k, v any) {
	if _, ok := d.vals[k]; !ok {
		d.keys = append(d.keys, k)
	}
	d.vals[k] = v
}

func (d *zincpyDict) Get(k any) any { return d.vals[k] }

// GetDefault is dict.get(k, default): the value if present, else default.
func (d *zincpyDict) GetDefault(k, def any) any {
	if v, ok := d.vals[k]; ok {
		return v
	}
	return def
}

// SetDefault is dict.setdefault(k, default): if k is present return its value;
// otherwise insert k=default (preserving order) and return default.
func (d *zincpyDict) SetDefault(k, def any) any {
	if v, ok := d.vals[k]; ok {
		return v
	}
	d.keys = append(d.keys, k)
	d.vals[k] = def
	return def
}

// Pop is dict.pop(k[, default]): remove k and return its value; with no default
// a missing key raises KeyError (Python parity), with one it returns default.
func (d *zincpyDict) Pop(k any, def ...any) any {
	if v, ok := d.vals[k]; ok {
		delete(d.vals, k)
		for i, kk := range d.keys {
			if kk == k {
				d.keys = append(d.keys[:i], d.keys[i+1:]...)
				break
			}
		}
		return v
	}
	if len(def) > 0 {
		return def[0]
	}
	panic(zincpyExc{Type: "KeyError", Msg: zincpyRepr(k)})
}

// Update is dict.update(other): merge another dict's entries, overwriting on
// key collision and appending new keys in the other's iteration order.
func (d *zincpyDict) Update(other *zincpyDict) {
	for _, k := range other.keys {
		d.Set(k, other.vals[k])
	}
}

func (d *zincpyDict) Has(k any) bool { _, ok := d.vals[k]; return ok }

func (d *zincpyDict) Len() int { return len(d.keys) }

func (d *zincpyDict) Keys() []any { return d.keys }

// Items returns the dict's (key, value) pairs as 2-tuples, in insertion order,
// for use by a for k, v in d.items() loop.
func (d *zincpyDict) Items() []any {
	out := make([]any, len(d.keys))
	for i, k := range d.keys {
		out[i] = zincpyTuple{items: []any{k, d.vals[k]}}
	}
	return out
}

func (d *zincpyDict) Values() []any {
	vs := make([]any, len(d.keys))
	for i, k := range d.keys {
		vs[i] = d.vals[k]
	}
	return vs
}

// String renders the dict the way CPython's repr does: {'a': 1, 'b': 2},
// keys/values via zincpyRepr, in insertion order.
func (d *zincpyDict) String() string {
	var b strings.Builder
	b.WriteByte('{')
	for i, k := range d.keys {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(zincpyRepr(k))
		b.WriteString(": ")
		b.WriteString(zincpyRepr(d.vals[k]))
	}
	b.WriteByte('}')
	return b.String()
}

// zincpyIn implements Python's "in" membership test, dispatching on the
// container: substring for strings, element search (value equality) for
// lists/tuples, key/element presence for dicts/sets.
func zincpyIn(needle, hay any) bool {
	switch h := hay.(type) {
	case string:
		s, ok := needle.(string)
		return ok && strings.Contains(h, s)
	case []any:
		for _, e := range h {
			if zincpyEq(e, needle) {
				return true
			}
		}
		return false
	case zincpyTuple:
		for _, e := range h.items {
			if zincpyEq(e, needle) {
				return true
			}
		}
		return false
	case *zincpyDict:
		return h.Has(needle)
	case *zincpySet:
		return h.Has(needle)
	}
	rv := reflect.ValueOf(hay)
	if rv.Kind() == reflect.Slice {
		for i := 0; i < rv.Len(); i++ {
			if zincpyEq(rv.Index(i).Interface(), needle) {
				return true
			}
		}
		return false
	}
	panic(zincpyExc{"TypeError", "argument of type " + zincpyTypeName(hay) + " is not iterable"})
}

// zincpySet is a Python set. Backed by insertion-ordered storage for
// deterministic iteration in OUR output; note this differs from CPython's
// hash-ordered iteration, so set iteration/printing order is not guaranteed to
// match CPython (use sorted() for stable output). repr: {a, b}, or set() empty.
type zincpySet struct {
	items []any
	has   map[any]bool
}

func zincpyNewSet() *zincpySet { return &zincpySet{has: map[any]bool{}} }

func zincpySetOf(xs any) *zincpySet {
	s := zincpyNewSet()
	for _, v := range zincpySeq(xs) {
		s.Add(v)
	}
	return s
}

func (s *zincpySet) Add(v any) {
	if !s.has[v] {
		s.has[v] = true
		s.items = append(s.items, v)
	}
}

func (s *zincpySet) Has(v any) bool { return s.has[v] }

func (s *zincpySet) Len() int { return len(s.items) }

func (s *zincpySet) Keys() []any { return s.items }

func (s *zincpySet) Discard(v any) {
	if s.has[v] {
		delete(s.has, v)
		for i, x := range s.items {
			if x == v {
				s.items = append(s.items[:i], s.items[i+1:]...)
				break
			}
		}
	}
}

func (s *zincpySet) Remove(v any) {
	if !s.has[v] {
		panic(zincpyExc{"KeyError", zincpyRepr(v)})
	}
	s.Discard(v)
}

func (s *zincpySet) String() string {
	if len(s.items) == 0 {
		return "set()"
	}
	var b strings.Builder
	b.WriteByte('{')
	for i, v := range s.items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(zincpyRepr(v))
	}
	b.WriteByte('}')
	return b.String()
}

// zincpyTuple is a Python tuple: a fixed, heterogeneous, immutable sequence.
// Elements are boxed (any); the front-end routes index/iterate/len on a tuple
// through the dynamic helpers. String() renders the way CPython repr does,
// including the one-element (x,) form.
type zincpyTuple struct {
	items []any
}

func zincpyNewTuple(items ...any) zincpyTuple { return zincpyTuple{items: items} }

func (t zincpyTuple) String() string {
	if len(t.items) == 1 {
		return "(" + zincpyRepr(t.items[0]) + ",)"
	}
	var b strings.Builder
	b.WriteByte('(')
	for i, v := range t.items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(zincpyRepr(v))
	}
	b.WriteByte(')')
	return b.String()
}

// zincpyExc models a Python exception: a type name plus a message. Raised via
// panic(zincpyExc{...}); String() returns the message so print(e)/str(e)
// match CPython.
type zincpyExc struct {
	Type string
	Msg  string
}

func (e zincpyExc) String() string { return e.Msg }

// zincpyExcParents is a subset of CPython's builtin exception hierarchy, used
// by zincpyMatch to honor subclass relationships in except clauses.
var zincpyExcParents = map[string]string{
	"ValueError":          "Exception",
	"TypeError":           "Exception",
	"KeyError":            "LookupError",
	"IndexError":          "LookupError",
	"LookupError":         "Exception",
	"ZeroDivisionError":   "ArithmeticError",
	"ArithmeticError":     "Exception",
	"RuntimeError":        "Exception",
	"NotImplementedError": "RuntimeError",
	"StopIteration":       "Exception",
	"AttributeError":      "Exception",
	"OSError":             "Exception",
	"Exception":           "BaseException",
}

// zincpyMatch reports whether a recovered panic value matches an except-clause
// type. An empty type is a bare except (matches anything). A non-zincpyExc
// panic (e.g. a Go runtime error) is treated as an Exception.
func zincpyMatch(exc any, typ string) bool {
	if typ == "" {
		return true
	}
	e, ok := exc.(zincpyExc)
	if !ok {
		return typ == "Exception" || typ == "BaseException"
	}
	for t := e.Type; t != ""; t = zincpyExcParents[t] {
		if t == typ {
			return true
		}
	}
	return false
}

// zincpyRepr is Python's repr() for the value kinds we emit: strings are
// single-quoted, bools are True/False, floats use Python float formatting.
func zincpyRepr(v any) string {
	switch x := v.(type) {
	case string:
		return "'" + x + "'"
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		return zincpyFloat(x)
	default:
		if s, ok := zincpySeqRepr(v); ok {
			return s
		}
		return fmt.Sprint(v)
	}
}

// zincpyIsInstance reports whether v is an instance of any of the named types,
// mirroring isinstance(obj, T) and isinstance(obj, (A, B)). Builtin type names
// match by the value's Go representation; a user-class name matches when v is
// that struct or embeds it (Go struct embedding mirrors the inheritance chain,
// walked via anonymous reflect fields).
func zincpyIsInstance(v any, names ...string) bool {
	for _, name := range names {
		if zincpyIsInstance1(v, name) {
			return true
		}
	}
	return false
}

func zincpyIsInstance1(v any, name string) bool {
	switch name {
	case "object":
		return true
	case "bool":
		_, ok := v.(bool)
		return ok
	case "int":
		// Python's bool is a subclass of int, so an int check accepts a bool.
		if _, ok := v.(bool); ok {
			return true
		}
		k := reflect.ValueOf(v).Kind()
		return k >= reflect.Int && k <= reflect.Uint64
	case "float":
		_, ok := v.(float64)
		return ok
	case "str":
		_, ok := v.(string)
		return ok
	case "list":
		rv := reflect.ValueOf(v)
		return rv.IsValid() && rv.Kind() == reflect.Slice
	case "dict":
		_, ok := v.(*zincpyDict)
		return ok
	case "set":
		_, ok := v.(*zincpySet)
		return ok
	case "tuple":
		_, ok := v.(zincpyTuple)
		return ok
	}
	// User class: match the struct's own name or any embedded (anonymous) field
	// up the chain.
	t := reflect.TypeOf(v)
	for t != nil && t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if t == nil || t.Kind() != reflect.Struct {
		return false
	}
	return zincpyStructIsA(t, name)
}

func zincpyStructIsA(t reflect.Type, name string) bool {
	if t.Name() == name {
		return true
	}
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.Anonymous {
			continue
		}
		ft := f.Type
		for ft.Kind() == reflect.Ptr {
			ft = ft.Elem()
		}
		if ft.Kind() == reflect.Struct && zincpyStructIsA(ft, name) {
			return true
		}
	}
	return false
}
`
