// Copyright 2026 victorybhg
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package pyfront

// RuntimeFileName is the name of the emitted Python-runtime shim file.
const RuntimeFileName = "zincpy_runtime.go"

// RuntimeGo is the Go source of the Python-runtime shim. It is emitted as a
// sibling file in the output module (package main) and provides the handful
// of functions the front-end lowers divergent Python semantics into. Keeping
// it as emitted source — rather than a Go-side dependency — means the output
// module stays self-contained and the helpers are visible in `--emit`.
//
// Every import here is used by a function body, so an output program that
// happens not to call a given helper still compiles (unused funcs are legal
// in Go; unused imports are not).
const RuntimeGo = `// Code generated by zincpy. DO NOT EDIT.
package main

import (
	"fmt"
	"math"
	"reflect"
	"sort"
	"strconv"
	"strings"
)

// zincpyPrint mirrors Python's print() for one value: Python str()
// formatting, newline-terminated.
func zincpyPrint(v any) {
	fmt.Println(zincpyStr(v))
}

// zincpyPrintN mirrors Python's print() for any number of arguments: each is
// str()-formatted and joined with a single space, newline-terminated. This is
// Python's default sep=' ', end='\n'.
func zincpyPrintN(vs ...any) {
	parts := make([]string, len(vs))
	for i, v := range vs {
		parts[i] = zincpyStr(v)
	}
	fmt.Println(strings.Join(parts, " "))
}

// zincpyUpper / zincpyLower mirror str.upper()/str.lower(). (ASCII-equivalent
// to Python; full Unicode case folding is a known gap.)
func zincpyUpper(s string) string { return strings.ToUpper(s) }
func zincpyLower(s string) string { return strings.ToLower(s) }

// zincpyStrip is str.strip(): no argument trims surrounding whitespace; an
// argument trims any of the given characters from both ends.
func zincpyStrip(s string, chars ...string) string {
	if len(chars) == 0 {
		return strings.TrimSpace(s)
	}
	return strings.Trim(s, chars[0])
}

// zincpyReplace is str.replace(old, new): replaces every occurrence (Python's
// default count of -1).
func zincpyReplace(s, old, replacement string) string {
	return strings.ReplaceAll(s, old, replacement)
}

// zincpyStartswith / zincpyEndswith mirror str.startswith()/str.endswith().
func zincpyStartswith(s, prefix string) bool { return strings.HasPrefix(s, prefix) }
func zincpyEndswith(s, suffix string) bool   { return strings.HasSuffix(s, suffix) }

// zincpyFind is str.find(): the byte index of the first occurrence, or -1.
func zincpyFind(s, sub string) int { return strings.Index(s, sub) }

// zincpyCount is str.count(): the number of non-overlapping occurrences.
func zincpyCount(s, sub string) int { return strings.Count(s, sub) }

// zincpySplit is str.split(): with no separator it splits on runs of
// whitespace and drops empty fields (Python's default); with a separator it
// splits on each occurrence.
func zincpySplit(s string, sep ...string) []string {
	if len(sep) == 0 {
		return strings.Fields(s)
	}
	return strings.Split(s, sep[0])
}

// zincpyJoin is sep.join(items): the receiver string joins the elements.
func zincpyJoin(sep string, items []string) string {
	return strings.Join(items, sep)
}

// zincpyStrMethod dispatches a str method called on a DYNAMIC receiver (an
// unannotated / duck-typed value the front-end could not lower to the typed
// helper). The receiver must be a string at run time — Python raises
// AttributeError otherwise — and string arguments are likewise asserted. The
// result is boxed (any) since the receiver's type was not known statically.
func zincpyStrMethod(recv any, method string, args ...any) any {
	s, ok := recv.(string)
	if !ok {
		panic(zincpyExc{"AttributeError", zincpyTypeName(recv) + " object has no attribute " + zincpyRepr(method)})
	}
	argStr := func(i int) string {
		a, ok := args[i].(string)
		if !ok {
			panic(zincpyExc{"TypeError", method + "() argument must be str, not " + zincpyTypeName(args[i])})
		}
		return a
	}
	switch method {
	case "upper":
		return zincpyUpper(s)
	case "lower":
		return zincpyLower(s)
	case "strip":
		if len(args) == 0 {
			return zincpyStrip(s)
		}
		return zincpyStrip(s, argStr(0))
	case "replace":
		return zincpyReplace(s, argStr(0), argStr(1))
	case "startswith":
		return zincpyStartswith(s, argStr(0))
	case "endswith":
		return zincpyEndswith(s, argStr(0))
	case "find":
		return zincpyFind(s, argStr(0))
	case "count":
		return zincpyCount(s, argStr(0))
	case "split":
		if len(args) == 0 {
			return zincpySplit(s)
		}
		return zincpySplit(s, argStr(0))
	case "join":
		items := zincpySeq(args[0])
		strs := make([]string, len(items))
		for i, item := range items {
			si, ok := item.(string)
			if !ok {
				panic(zincpyExc{"TypeError", "sequence item " + strconv.Itoa(i) + ": expected str instance, " + zincpyTypeName(item) + " found"})
			}
			strs[i] = si
		}
		return zincpyJoin(s, strs)
	}
	panic(zincpyExc{"AttributeError", "str object has no attribute " + zincpyRepr(method)})
}

// --- dynamic-value operations ------------------------------------------------
//
// These dispatch on the boxed runtime type of a dynamic value (an FFI result
// or something derived from one). The front-end routes index/iterate/len and
// numeric coercion on a dynamic value here instead of emitting native Go,
// which cannot operate on an interface{}.

// zincpyGetItem is Python subscription d[k] on a dynamic value: sequence
// indexing (with negative-index wraparound) for lists and strings, key lookup
// for dicts.
func zincpyGetItem(container, key any) any {
	switch c := container.(type) {
	case []any:
		i := key.(int)
		if i < 0 {
			i += len(c)
		}
		if i < 0 || i >= len(c) {
			panic(zincpyExc{"IndexError", "list index out of range"})
		}
		return c[i]
	case zincpyTuple:
		i := key.(int)
		if i < 0 {
			i += len(c.items)
		}
		if i < 0 || i >= len(c.items) {
			panic(zincpyExc{"IndexError", "tuple index out of range"})
		}
		return c.items[i]
	case *zincpyDict:
		if !c.Has(key) {
			panic(zincpyExc{"KeyError", zincpyRepr(key)})
		}
		return c.Get(key)
	case string:
		rs := []rune(c)
		i := key.(int)
		if i < 0 {
			i += len(rs)
		}
		if i < 0 || i >= len(rs) {
			panic(zincpyExc{"IndexError", "string index out of range"})
		}
		return string(rs[i])
	}
	// A typed slice (e.g. []int) reaching here was boxed into a dynamic value
	// (passed to an unannotated param); index it reflectively.
	if rv := reflect.ValueOf(container); rv.IsValid() && rv.Kind() == reflect.Slice {
		i := key.(int)
		if i < 0 {
			i += rv.Len()
		}
		if i < 0 || i >= rv.Len() {
			panic(zincpyExc{"IndexError", "list index out of range"})
		}
		return rv.Index(i).Interface()
	}
	panic(zincpyExc{"TypeError", "object is not subscriptable"})
}

// zincpyIter yields the elements to range over for a for-in loop on a dynamic
// value: list elements, dict keys (insertion order), or string characters.
func zincpyIter(container any) []any {
	switch c := container.(type) {
	case []any:
		return c
	case zincpyTuple:
		return c.items
	case *zincpyDict:
		return c.Keys()
	case string:
		rs := []rune(c)
		out := make([]any, len(rs))
		for i, r := range rs {
			out[i] = string(r)
		}
		return out
	}
	// Sets and arbitrary typed slices (boxed into a dynamic value) — materialize
	// reflectively. zincpySeq raises the same TypeError for non-iterables.
	return zincpySeq(container)
}

// zincpyLen is len() on a dynamic value.
func zincpyLen(container any) int {
	switch c := container.(type) {
	case []any:
		return len(c)
	case zincpyTuple:
		return len(c.items)
	case *zincpyDict:
		return c.Len()
	case string:
		return len([]rune(c))
	case *zincpySet:
		return c.Len()
	}
	// A typed slice/map/array boxed into a dynamic value.
	if rv := reflect.ValueOf(container); rv.IsValid() {
		switch rv.Kind() {
		case reflect.Slice, reflect.Map, reflect.Array:
			return rv.Len()
		}
	}
	panic(zincpyExc{"TypeError", "object has no len()"})
}

// zincpyToFloat is Python float() on a dynamic value.
func zincpyToFloat(v any) float64 {
	switch x := v.(type) {
	case float64:
		return x
	case int:
		return float64(x)
	case bool:
		if x {
			return 1
		}
		return 0
	case string:
		f, err := strconv.ParseFloat(strings.TrimSpace(x), 64)
		if err != nil {
			panic(zincpyExc{"ValueError", "could not convert string to float: " + zincpyRepr(x)})
		}
		return f
	}
	panic(zincpyExc{"TypeError", "float() argument must be a string or a number"})
}

// zincpyToInt is Python int() on a dynamic value; float truncates toward zero.
func zincpyToInt(v any) int {
	switch x := v.(type) {
	case int:
		return x
	case float64:
		return int(x)
	case bool:
		if x {
			return 1
		}
		return 0
	case string:
		n, err := strconv.Atoi(strings.TrimSpace(x))
		if err != nil {
			panic(zincpyExc{"ValueError", "invalid literal for int() with base 10: " + zincpyRepr(x)})
		}
		return n
	}
	panic(zincpyExc{"TypeError", "int() argument must be a string or a number"})
}

// zincpyToBool coerces a dynamic value to a Go bool for a bool-typed return: a
// genuine bool passes through; anything else falls back to Python truthiness.
func zincpyToBool(v any) bool {
	if b, ok := v.(bool); ok {
		return b
	}
	return zincpyTruthy(v)
}

// --- dynamic binary operators ------------------------------------------------
//
// When an operand of a binary op is dynamic, the front-end can't pick a Go
// operator statically, so it emits one of these. They reproduce Python's
// operator overloading: numeric tower (int stays int; any float widens),
// str/list/tuple concatenation, and sequence repetition.

func zincpyTypeName(v any) string {
	switch v.(type) {
	case int:
		return "'int'"
	case float64:
		return "'float'"
	case string:
		return "'str'"
	case bool:
		return "'bool'"
	case []any:
		return "'list'"
	case *zincpyDict:
		return "'dict'"
	case zincpyTuple:
		return "'tuple'"
	case nil:
		return "'NoneType'"
	}
	return "'object'"
}

// zincpyIntish reports an integer value for int/bool (Python treats bool as a
// subclass of int, so True + 1 == 2).
func zincpyIntish(v any) (int, bool) {
	switch x := v.(type) {
	case int:
		return x, true
	case bool:
		if x {
			return 1, true
		}
		return 0, true
	}
	return 0, false
}

func zincpyNum(v any) (float64, bool) {
	switch x := v.(type) {
	case float64:
		return x, true
	case int:
		return float64(x), true
	case bool:
		if x {
			return 1, true
		}
		return 0, true
	}
	return 0, false
}

// zincpyIdx normalizes a (possibly negative) sequence index against the
// length, matching Python: xs[-1] is the last element. Positive indices pass
// through unchanged.
func zincpyIdx(i, n int) int {
	if i < 0 {
		return i + n
	}
	return i
}

// zincpyNeg is unary minus on a dynamic value.
func zincpyNeg(v any) any {
	switch x := v.(type) {
	case int:
		return -x
	case float64:
		return -x
	case bool:
		if x {
			return -1
		}
		return 0
	}
	panic(zincpyExc{"TypeError", "bad operand type for unary -: " + zincpyTypeName(v)})
}

func zincpyAdd(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return ai + bi
		}
	}
	if af, ok := zincpyNum(a); ok {
		if bf, ok := zincpyNum(b); ok {
			return af + bf
		}
	}
	if as, ok := a.(string); ok {
		if bs, ok := b.(string); ok {
			return as + bs
		}
	}
	if al, ok := a.([]any); ok {
		if bl, ok := b.([]any); ok {
			r := make([]any, 0, len(al)+len(bl))
			return append(append(r, al...), bl...)
		}
	}
	if at, ok := a.(zincpyTuple); ok {
		if bt, ok := b.(zincpyTuple); ok {
			it := make([]any, 0, len(at.items)+len(bt.items))
			return zincpyTuple{items: append(append(it, at.items...), bt.items...)}
		}
	}
	// Typed slices (e.g. []int) boxed into dynamic values concatenate like
	// lists, producing a []any (matching Python list +).
	if ra, rb := reflect.ValueOf(a), reflect.ValueOf(b); ra.IsValid() && rb.IsValid() &&
		ra.Kind() == reflect.Slice && rb.Kind() == reflect.Slice {
		r := make([]any, 0, ra.Len()+rb.Len())
		for i := 0; i < ra.Len(); i++ {
			r = append(r, ra.Index(i).Interface())
		}
		for i := 0; i < rb.Len(); i++ {
			r = append(r, rb.Index(i).Interface())
		}
		return r
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for +: " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
}

func zincpySub(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return ai - bi
		}
	}
	if af, ok := zincpyNum(a); ok {
		if bf, ok := zincpyNum(b); ok {
			return af - bf
		}
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for -: " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
}

func zincpyMul(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return ai * bi
		}
	}
	if af, ok := zincpyNum(a); ok {
		if bf, ok := zincpyNum(b); ok {
			return af * bf
		}
	}
	// sequence repetition: str*int and list*int (either order)
	if s, n, ok := zincpyStrRepeat(a, b); ok {
		return strings.Repeat(s, n)
	}
	if lst, n, ok := zincpyListRepeat(a, b); ok {
		out := make([]any, 0, len(lst)*n)
		for i := 0; i < n; i++ {
			out = append(out, lst...)
		}
		return out
	}
	panic(zincpyExc{"TypeError", "can't multiply " + zincpyTypeName(a) + " by " + zincpyTypeName(b)})
}

func zincpyStrRepeat(a, b any) (string, int, bool) {
	if s, ok := a.(string); ok {
		if n, ok := zincpyIntish(b); ok {
			return s, n, true
		}
	}
	if s, ok := b.(string); ok {
		if n, ok := zincpyIntish(a); ok {
			return s, n, true
		}
	}
	return "", 0, false
}

func zincpyListRepeat(a, b any) ([]any, int, bool) {
	if l, ok := a.([]any); ok {
		if n, ok := zincpyIntish(b); ok {
			return l, n, true
		}
	}
	if l, ok := b.([]any); ok {
		if n, ok := zincpyIntish(a); ok {
			return l, n, true
		}
	}
	return nil, 0, false
}

// zincpyTrueDiv is Python / on dynamic operands: always float, /0 raises.
func zincpyTrueDiv(a, b any) float64 {
	af, ao := zincpyNum(a)
	bf, bo := zincpyNum(b)
	if !ao || !bo {
		panic(zincpyExc{"TypeError", "unsupported operand type(s) for /: " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
	}
	if bf == 0 {
		panic(zincpyExc{"ZeroDivisionError", "division by zero"})
	}
	return af / bf
}

// zincpyFloorDivDyn / zincpyModDyn are Python // and % on dynamic operands:
// int-int stays int with floor/sign-of-divisor semantics; float operands use
// math.Floor.
func zincpyFloorDivDyn(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return zincpyFloorDiv(ai, bi)
		}
	}
	af, ao := zincpyNum(a)
	bf, bo := zincpyNum(b)
	if ao && bo {
		if bf == 0 {
			panic(zincpyExc{"ZeroDivisionError", "float floor division by zero"})
		}
		return math.Floor(af / bf)
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for //"})
}

func zincpyModDyn(a, b any) any {
	if ai, ok := zincpyIntish(a); ok {
		if bi, ok := zincpyIntish(b); ok {
			return zincpyMod(ai, bi)
		}
	}
	af, ao := zincpyNum(a)
	bf, bo := zincpyNum(b)
	if ao && bo {
		if bf == 0 {
			panic(zincpyExc{"ZeroDivisionError", "float modulo"})
		}
		m := math.Mod(af, bf)
		if m != 0 && (m < 0) != (bf < 0) {
			m += bf
		}
		return m
	}
	panic(zincpyExc{"TypeError", "unsupported operand type(s) for %"})
}

// zincpyEq / zincpyNe / ordering compare dynamic operands the Python way:
// numbers compare across int/float, strings lexically.
func zincpyEq(a, b any) bool {
	if af, ao := zincpyNum(a); ao {
		if bf, bo := zincpyNum(b); bo {
			return af == bf
		}
	}
	return reflect.DeepEqual(a, b)
}

func zincpyNe(a, b any) bool { return !zincpyEq(a, b) }

func zincpyCmp(a, b any) int {
	if af, ao := zincpyNum(a); ao {
		if bf, bo := zincpyNum(b); bo {
			switch {
			case af < bf:
				return -1
			case af > bf:
				return 1
			default:
				return 0
			}
		}
	}
	if as, ok := a.(string); ok {
		if bs, ok := b.(string); ok {
			return strings.Compare(as, bs)
		}
	}
	panic(zincpyExc{"TypeError", "'<' not supported between instances of " + zincpyTypeName(a) + " and " + zincpyTypeName(b)})
}

func zincpyLt(a, b any) bool { return zincpyCmp(a, b) < 0 }
func zincpyGt(a, b any) bool { return zincpyCmp(a, b) > 0 }
func zincpyLe(a, b any) bool { return zincpyCmp(a, b) <= 0 }
func zincpyGe(a, b any) bool { return zincpyCmp(a, b) >= 0 }

// zincpyTruthy implements Python truthiness for a condition value: None, zero
// numbers, empty string, and empty containers are falsy; everything else
// (including any object) is truthy.
func zincpyTruthy(v any) bool {
	switch x := v.(type) {
	case nil:
		return false
	case bool:
		return x
	case int:
		return x != 0
	case float64:
		return x != 0
	case string:
		return x != ""
	case []any:
		return len(x) != 0
	case zincpyTuple:
		return len(x.items) != 0
	case *zincpyDict:
		return x.Len() != 0
	case *zincpySet:
		return x.Len() != 0
	}
	rv := reflect.ValueOf(v)
	switch rv.Kind() {
	case reflect.Slice, reflect.Map, reflect.Array:
		return rv.Len() != 0
	}
	return true
}

// --- builtins over sequences -------------------------------------------------
//
// min/max/sum/sorted accept any slice kind (the front-end's homogeneous list
// literals become concrete Go slices), so they reflect over the elements and
// return boxed (dynamic) results.

func zincpySeq(xs any) []any {
	rv := reflect.ValueOf(xs)
	if !rv.IsValid() || rv.Kind() != reflect.Slice {
		switch v := xs.(type) {
		case string:
			rs := []rune(v)
			out := make([]any, len(rs))
			for i, r := range rs {
				out[i] = string(r)
			}
			return out
		case zincpyTuple:
			return v.items
		case *zincpyDict:
			return v.Keys()
		case *zincpySet:
			return v.Keys()
		}
		panic(zincpyExc{"TypeError", "object is not iterable"})
	}
	out := make([]any, rv.Len())
	for i := range out {
		out[i] = rv.Index(i).Interface()
	}
	return out
}

func zincpyMin(xs any) any {
	s := zincpySeq(xs)
	if len(s) == 0 {
		panic(zincpyExc{"ValueError", "min() arg is an empty sequence"})
	}
	best := s[0]
	for _, v := range s[1:] {
		if zincpyCmp(v, best) < 0 {
			best = v
		}
	}
	return best
}

func zincpyMax(xs any) any {
	s := zincpySeq(xs)
	if len(s) == 0 {
		panic(zincpyExc{"ValueError", "max() arg is an empty sequence"})
	}
	best := s[0]
	for _, v := range s[1:] {
		if zincpyCmp(v, best) > 0 {
			best = v
		}
	}
	return best
}

// zincpySum mirrors Python sum(): result is int unless any element is float.
func zincpySum(xs any) any {
	s := zincpySeq(xs)
	isum, fsum, isFloat := 0, 0.0, false
	for _, v := range s {
		switch x := v.(type) {
		case int:
			isum += x
			fsum += float64(x)
		case bool:
			if x {
				isum++
				fsum++
			}
		case float64:
			isFloat = true
			fsum += x
		default:
			panic(zincpyExc{"TypeError", "unsupported operand type for sum(): " + zincpyTypeName(v)})
		}
	}
	if isFloat {
		return fsum
	}
	return isum
}

func zincpySorted(xs any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	copy(out, s)
	sort.SliceStable(out, func(i, j int) bool { return zincpyCmp(out[i], out[j]) < 0 })
	return out
}

// zincpySortedKey is sorted(xs, key=f): order by f(element).
func zincpySortedKey(xs any, key func(any) any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	copy(out, s)
	sort.SliceStable(out, func(i, j int) bool { return zincpyCmp(key(out[i]), key(out[j])) < 0 })
	return out
}

// zincpyList is list(x): materialize any iterable into a new []any.
func zincpyList(xs any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	copy(out, s)
	return out
}

// zincpyMap is map(f, xs): f applied to each element.
func zincpyMap(f func(any) any, xs any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	for i, v := range s {
		out[i] = f(v)
	}
	return out
}

// zincpyFilter is filter(f, xs): elements where f(element) is truthy.
func zincpyFilter(f func(any) any, xs any) []any {
	var out []any
	for _, v := range zincpySeq(xs) {
		if zincpyTruthy(f(v)) {
			out = append(out, v)
		}
	}
	return out
}

// zincpySlice implements Python slicing seq[start:stop:step] on a list, string,
// or tuple. start/stop/step are int or nil (omitted). Negative indices and
// negative step are handled per CPython; the result is a new list/string/tuple.
func zincpySlice(seq, startA, stopA, stepA any) any {
	step := 1
	if stepA != nil {
		step = stepA.(int)
		if step == 0 {
			panic(zincpyExc{"ValueError", "slice step cannot be zero"})
		}
	}
	switch s := seq.(type) {
	case string:
		rs := []rune(s)
		var b strings.Builder
		for _, i := range zincpySliceIndices(len(rs), startA, stopA, step) {
			b.WriteRune(rs[i])
		}
		return b.String()
	case zincpyTuple:
		idxs := zincpySliceIndices(len(s.items), startA, stopA, step)
		out := make([]any, len(idxs))
		for k, i := range idxs {
			out[k] = s.items[i]
		}
		return zincpyTuple{items: out}
	}
	elems := zincpySeq(seq)
	idxs := zincpySliceIndices(len(elems), startA, stopA, step)
	out := make([]any, len(idxs))
	for k, i := range idxs {
		out[k] = elems[i]
	}
	return out
}

// zincpySliceIndices returns the concrete indices a slice selects, mirroring
// CPython's slice.indices(length).
func zincpySliceIndices(n int, startA, stopA any, step int) []int {
	lower, upper := 0, n
	if step < 0 {
		lower, upper = -1, n-1
	}
	clamp := func(i int) int {
		if i < lower {
			return lower
		}
		if i > upper {
			return upper
		}
		return i
	}
	var start, stop int
	if startA == nil {
		if step < 0 {
			start = upper
		} else {
			start = lower
		}
	} else {
		start = startA.(int)
		if start < 0 {
			start += n
		}
		start = clamp(start)
	}
	if stopA == nil {
		if step < 0 {
			stop = lower
		} else {
			stop = upper
		}
	} else {
		stop = stopA.(int)
		if stop < 0 {
			stop += n
		}
		stop = clamp(stop)
	}
	var idxs []int
	if step > 0 {
		for i := start; i < stop; i += step {
			idxs = append(idxs, i)
		}
	} else {
		for i := start; i > stop; i += step {
			idxs = append(idxs, i)
		}
	}
	return idxs
}

// zincpyEnumerate mirrors enumerate(xs): (index, element) 2-tuples.
func zincpyEnumerate(xs any) []any {
	s := zincpySeq(xs)
	out := make([]any, len(s))
	for i, v := range s {
		out[i] = zincpyTuple{items: []any{i, v}}
	}
	return out
}

// zincpyZip mirrors zip(a, b, ...): tuples of corresponding elements, stopping
// at the shortest input.
func zincpyZip(args ...any) []any {
	if len(args) == 0 {
		return nil
	}
	seqs := make([][]any, len(args))
	minLen := -1
	for i, a := range args {
		seqs[i] = zincpySeq(a)
		if minLen < 0 || len(seqs[i]) < minLen {
			minLen = len(seqs[i])
		}
	}
	out := make([]any, minLen)
	for i := 0; i < minLen; i++ {
		tup := make([]any, len(seqs))
		for j := range seqs {
			tup[j] = seqs[j][i]
		}
		out[i] = zincpyTuple{items: tup}
	}
	return out
}

func zincpyAbs(v any) any {
	switch x := v.(type) {
	case int:
		if x < 0 {
			return -x
		}
		return x
	case float64:
		return math.Abs(x)
	case bool:
		if x {
			return 1
		}
		return 0
	}
	panic(zincpyExc{"TypeError", "bad operand type for abs(): " + zincpyTypeName(v)})
}

// zincpyStr mirrors Python's str() for the value kinds the front-end emits.
func zincpyStr(v any) string {
	switch x := v.(type) {
	case float64:
		return zincpyFloat(x)
	case bool:
		if x {
			return "True"
		}
		return "False"
	case string:
		return x
	default:
		if s, ok := zincpySeqRepr(v); ok {
			return s
		}
		return fmt.Sprint(v)
	}
}

// zincpySeqRepr renders a Go slice the way Python repr renders a list:
// [e0, e1, ...] with each element via zincpyRepr (so strings are quoted and
// floats/bools use Python formatting). Returns ok=false for non-slices.
// str(list) and repr(list) are identical in Python, so both paths use this.
func zincpySeqRepr(v any) (string, bool) {
	rv := reflect.ValueOf(v)
	if !rv.IsValid() || rv.Kind() != reflect.Slice {
		return "", false
	}
	var b strings.Builder
	b.WriteByte('[')
	for i := 0; i < rv.Len(); i++ {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(zincpyRepr(rv.Index(i).Interface()))
	}
	b.WriteByte(']')
	return b.String(), true
}

// zincpyFloat formats a float the way CPython's repr/str does for the common
// (non-astronomical) range: shortest round-trip digits, with a decimal point
// forced for integer-valued floats (3 -> "3.0"). Scientific-notation
// threshold differences vs CPython are a known gap for very large/small
// magnitudes.
func zincpyFloat(f float64) string {
	switch {
	case math.IsNaN(f):
		return "nan"
	case math.IsInf(f, 1):
		return "inf"
	case math.IsInf(f, -1):
		return "-inf"
	}
	s := strconv.FormatFloat(f, 'g', -1, 64)
	for i := 0; i < len(s); i++ {
		if s[i] == '.' || s[i] == 'e' {
			return s
		}
	}
	return s + ".0"
}

// zincpyDiv is Python true division: always float, and division by zero raises
// ZeroDivisionError (Go float division would yield +Inf instead).
func zincpyDiv(a, b float64) float64 {
	if b == 0 {
		panic(zincpyExc{"ZeroDivisionError", "division by zero"})
	}
	return a / b
}

// zincpyFloorDiv is Python's // on ints: floor toward negative infinity.
// Go's / truncates toward zero, so the two differ when the operands have
// opposite signs and the division is inexact. Division by zero raises
// ZeroDivisionError (matching CPython, not a Go runtime panic).
func zincpyFloorDiv(a, b int) int {
	if b == 0 {
		panic(zincpyExc{"ZeroDivisionError", "integer division or modulo by zero"})
	}
	q := a / b
	if (a%b != 0) && ((a < 0) != (b < 0)) {
		q--
	}
	return q
}

// zincpyMod is Python's % on ints: the result takes the sign of the divisor.
// Go's % takes the sign of the dividend, so e.g. -7 % 3 is -1 in Go but 2 in
// Python.
func zincpyMod(a, b int) int {
	if b == 0 {
		panic(zincpyExc{"ZeroDivisionError", "integer division or modulo by zero"})
	}
	return ((a % b) + b) % b
}

// zincpyDict is an insertion-ordered map — Python dict semantics. Go's
// built-in map randomizes iteration order, so iteration/keys/values/printing
// would diverge from CPython without tracking insertion order explicitly.
// Keys and values are boxed (any); the front-end inserts type assertions on
// Get where the value type is known.
type zincpyDict struct {
	keys []any
	vals map[any]any
}

func zincpyNewDict() *zincpyDict {
	return &zincpyDict{vals: map[any]any{}}
}

func (d *zincpyDict) Set(k, v any) {
	if _, ok := d.vals[k]; !ok {
		d.keys = append(d.keys, k)
	}
	d.vals[k] = v
}

func (d *zincpyDict) Get(k any) any { return d.vals[k] }

func (d *zincpyDict) Has(k any) bool { _, ok := d.vals[k]; return ok }

func (d *zincpyDict) Len() int { return len(d.keys) }

func (d *zincpyDict) Keys() []any { return d.keys }

// Items returns the dict's (key, value) pairs as 2-tuples, in insertion order,
// for use by a for k, v in d.items() loop.
func (d *zincpyDict) Items() []any {
	out := make([]any, len(d.keys))
	for i, k := range d.keys {
		out[i] = zincpyTuple{items: []any{k, d.vals[k]}}
	}
	return out
}

func (d *zincpyDict) Values() []any {
	vs := make([]any, len(d.keys))
	for i, k := range d.keys {
		vs[i] = d.vals[k]
	}
	return vs
}

// String renders the dict the way CPython's repr does: {'a': 1, 'b': 2},
// keys/values via zincpyRepr, in insertion order.
func (d *zincpyDict) String() string {
	var b strings.Builder
	b.WriteByte('{')
	for i, k := range d.keys {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(zincpyRepr(k))
		b.WriteString(": ")
		b.WriteString(zincpyRepr(d.vals[k]))
	}
	b.WriteByte('}')
	return b.String()
}

// zincpyIn implements Python's "in" membership test, dispatching on the
// container: substring for strings, element search (value equality) for
// lists/tuples, key/element presence for dicts/sets.
func zincpyIn(needle, hay any) bool {
	switch h := hay.(type) {
	case string:
		s, ok := needle.(string)
		return ok && strings.Contains(h, s)
	case []any:
		for _, e := range h {
			if zincpyEq(e, needle) {
				return true
			}
		}
		return false
	case zincpyTuple:
		for _, e := range h.items {
			if zincpyEq(e, needle) {
				return true
			}
		}
		return false
	case *zincpyDict:
		return h.Has(needle)
	case *zincpySet:
		return h.Has(needle)
	}
	rv := reflect.ValueOf(hay)
	if rv.Kind() == reflect.Slice {
		for i := 0; i < rv.Len(); i++ {
			if zincpyEq(rv.Index(i).Interface(), needle) {
				return true
			}
		}
		return false
	}
	panic(zincpyExc{"TypeError", "argument of type " + zincpyTypeName(hay) + " is not iterable"})
}

// zincpySet is a Python set. Backed by insertion-ordered storage for
// deterministic iteration in OUR output; note this differs from CPython's
// hash-ordered iteration, so set iteration/printing order is not guaranteed to
// match CPython (use sorted() for stable output). repr: {a, b}, or set() empty.
type zincpySet struct {
	items []any
	has   map[any]bool
}

func zincpyNewSet() *zincpySet { return &zincpySet{has: map[any]bool{}} }

func zincpySetOf(xs any) *zincpySet {
	s := zincpyNewSet()
	for _, v := range zincpySeq(xs) {
		s.Add(v)
	}
	return s
}

func (s *zincpySet) Add(v any) {
	if !s.has[v] {
		s.has[v] = true
		s.items = append(s.items, v)
	}
}

func (s *zincpySet) Has(v any) bool { return s.has[v] }

func (s *zincpySet) Len() int { return len(s.items) }

func (s *zincpySet) Keys() []any { return s.items }

func (s *zincpySet) Discard(v any) {
	if s.has[v] {
		delete(s.has, v)
		for i, x := range s.items {
			if x == v {
				s.items = append(s.items[:i], s.items[i+1:]...)
				break
			}
		}
	}
}

func (s *zincpySet) Remove(v any) {
	if !s.has[v] {
		panic(zincpyExc{"KeyError", zincpyRepr(v)})
	}
	s.Discard(v)
}

func (s *zincpySet) String() string {
	if len(s.items) == 0 {
		return "set()"
	}
	var b strings.Builder
	b.WriteByte('{')
	for i, v := range s.items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(zincpyRepr(v))
	}
	b.WriteByte('}')
	return b.String()
}

// zincpyTuple is a Python tuple: a fixed, heterogeneous, immutable sequence.
// Elements are boxed (any); the front-end routes index/iterate/len on a tuple
// through the dynamic helpers. String() renders the way CPython repr does,
// including the one-element (x,) form.
type zincpyTuple struct {
	items []any
}

func zincpyNewTuple(items ...any) zincpyTuple { return zincpyTuple{items: items} }

func (t zincpyTuple) String() string {
	if len(t.items) == 1 {
		return "(" + zincpyRepr(t.items[0]) + ",)"
	}
	var b strings.Builder
	b.WriteByte('(')
	for i, v := range t.items {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(zincpyRepr(v))
	}
	b.WriteByte(')')
	return b.String()
}

// zincpyExc models a Python exception: a type name plus a message. Raised via
// panic(zincpyExc{...}); String() returns the message so print(e)/str(e)
// match CPython.
type zincpyExc struct {
	Type string
	Msg  string
}

func (e zincpyExc) String() string { return e.Msg }

// zincpyExcParents is a subset of CPython's builtin exception hierarchy, used
// by zincpyMatch to honor subclass relationships in except clauses.
var zincpyExcParents = map[string]string{
	"ValueError":          "Exception",
	"TypeError":           "Exception",
	"KeyError":            "LookupError",
	"IndexError":          "LookupError",
	"LookupError":         "Exception",
	"ZeroDivisionError":   "ArithmeticError",
	"ArithmeticError":     "Exception",
	"RuntimeError":        "Exception",
	"NotImplementedError": "RuntimeError",
	"StopIteration":       "Exception",
	"AttributeError":      "Exception",
	"OSError":             "Exception",
	"Exception":           "BaseException",
}

// zincpyMatch reports whether a recovered panic value matches an except-clause
// type. An empty type is a bare except (matches anything). A non-zincpyExc
// panic (e.g. a Go runtime error) is treated as an Exception.
func zincpyMatch(exc any, typ string) bool {
	if typ == "" {
		return true
	}
	e, ok := exc.(zincpyExc)
	if !ok {
		return typ == "Exception" || typ == "BaseException"
	}
	for t := e.Type; t != ""; t = zincpyExcParents[t] {
		if t == typ {
			return true
		}
	}
	return false
}

// zincpyRepr is Python's repr() for the value kinds we emit: strings are
// single-quoted, bools are True/False, floats use Python float formatting.
func zincpyRepr(v any) string {
	switch x := v.(type) {
	case string:
		return "'" + x + "'"
	case bool:
		if x {
			return "True"
		}
		return "False"
	case float64:
		return zincpyFloat(x)
	default:
		if s, ok := zincpySeqRepr(v); ok {
			return s
		}
		return fmt.Sprint(v)
	}
}

// zincpyIsInstance reports whether v is an instance of any of the named types,
// mirroring isinstance(obj, T) and isinstance(obj, (A, B)). Builtin type names
// match by the value's Go representation; a user-class name matches when v is
// that struct or embeds it (Go struct embedding mirrors the inheritance chain,
// walked via anonymous reflect fields).
func zincpyIsInstance(v any, names ...string) bool {
	for _, name := range names {
		if zincpyIsInstance1(v, name) {
			return true
		}
	}
	return false
}

func zincpyIsInstance1(v any, name string) bool {
	switch name {
	case "object":
		return true
	case "bool":
		_, ok := v.(bool)
		return ok
	case "int":
		// Python's bool is a subclass of int, so an int check accepts a bool.
		if _, ok := v.(bool); ok {
			return true
		}
		k := reflect.ValueOf(v).Kind()
		return k >= reflect.Int && k <= reflect.Uint64
	case "float":
		_, ok := v.(float64)
		return ok
	case "str":
		_, ok := v.(string)
		return ok
	case "list":
		rv := reflect.ValueOf(v)
		return rv.IsValid() && rv.Kind() == reflect.Slice
	case "dict":
		_, ok := v.(*zincpyDict)
		return ok
	case "set":
		_, ok := v.(*zincpySet)
		return ok
	case "tuple":
		_, ok := v.(zincpyTuple)
		return ok
	}
	// User class: match the struct's own name or any embedded (anonymous) field
	// up the chain.
	t := reflect.TypeOf(v)
	for t != nil && t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if t == nil || t.Kind() != reflect.Struct {
		return false
	}
	return zincpyStructIsA(t, name)
}

func zincpyStructIsA(t reflect.Type, name string) bool {
	if t.Name() == name {
		return true
	}
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if !f.Anonymous {
			continue
		}
		ft := f.Type
		for ft.Kind() == reflect.Ptr {
			ft = ft.Elem()
		}
		if ft.Kind() == reflect.Struct && zincpyStructIsA(ft, name) {
			return true
		}
	}
	return false
}
`
