// Copyright 2026 victorybhg
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

package zinc.compiler;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Emits Python 3.14t source from a Zinc AST.
 * Bypasses the Transformer (JavaParser) entirely — walks Ast.Program directly.
 * Delegates to PythonDeclEmitter, PythonStmtEmitter, PythonExprEmitter, PythonTypeEmitter.
 */
public class PythonEmitter {

    private final PythonEmitContext ctx;
    private final PythonTypeEmitter types;
    private final PythonExprEmitter exprs;
    private final PythonStmtEmitter stmts;
    private final PythonDeclEmitter decls;

    public PythonEmitter(String className) {
        this.ctx = new PythonEmitContext(className);
        this.types = new PythonTypeEmitter(ctx);
        this.exprs = new PythonExprEmitter(ctx, types);
        this.stmts = new PythonStmtEmitter(ctx, exprs, types);
        this.decls = new PythonDeclEmitter(ctx, exprs, types, stmts);
        this.exprs.setStmtEmitter(stmts); // break circular dependency
    }

    /** Set the names of other .zn modules in the project (for relative imports). */
    public void setProjectModules(Set<String> modules) {
        ctx.projectModules = modules;
    }

    /** Set this module's subpackage (e.g. "services" for services/greeting.zn). */
    public void setModulePackage(String pkg) {
        ctx.modulePackage = pkg;
    }

    // --- Public API -----------------------------------------------------------

    /**
     * Emit a Zinc program as a single .py file.
     */
    public Result<Path> emit(Ast.Program program, Path outDir) {
        ctx.sb.setLength(0);
        ctx.imports.clear();
        ctx.fromImports.clear();

        // Resolve imports — project-local modules first, then target runtime
        for (var imp : program.imports()) {
            String path = imp.path();
            String pathLower = path.toLowerCase();

            int depth = ctx.modulePackage.isEmpty() ? 0 : ctx.modulePackage.split("\\.").length;
            String relPrefix = ".".repeat(depth + 1);

            if (ctx.projectModules.contains(pathLower)) {
                ctx.addFromImport("from " + relPrefix + pathLower + " import *");
                continue;
            }

            int lastDot = path.lastIndexOf('.');
            if (lastDot > 0) {
                String modulepart = path.substring(0, lastDot).toLowerCase();
                String name = path.substring(lastDot + 1);
                if (ctx.projectModules.contains(modulepart)) {
                    ctx.addFromImport("from " + relPrefix + modulepart + " import " + (name.equals("*") ? "*" : name));
                    continue;
                }
            }

            String firstSegment = path.contains(".") ? path.substring(0, path.indexOf('.')).toLowerCase() : pathLower;
            if (ctx.projectModules.contains(firstSegment)) {
                if (path.contains(".")) {
                    String rest = path.substring(path.indexOf('.') + 1);
                    ctx.addFromImport("from " + relPrefix + firstSegment + " import " + (rest.equals("*") ? "*" : rest));
                } else {
                    ctx.addFromImport("from " + relPrefix + firstSegment + " import *");
                }
                continue;
            }

            String resolved = ctx.target.resolveImport(path);
            if (resolved != null) {
                ctx.addFromImport(resolved);
            }
        }

        // Collect body first (so imports accumulate)
        var body = new StringBuilder();
        var savedSb = ctx.sb;
        ctx.sb = body;

        // Emit all declarations
        for (var decl : program.decls()) {
            decls.emitTopLevelDecl(decl);
            ctx.blank();
        }

        // Determine if there's an explicit main function
        boolean hasMainFn = program.decls().stream()
            .anyMatch(d -> d instanceof Ast.FnDecl fn && fn.name().equals("main"));

        // Script mode: top-level statements wrapped in main()
        if (!program.stmts().isEmpty() && !hasMainFn) {
            ctx.line("def main():");
            ctx.indent++;
            for (var stmt : program.stmts()) {
                stmts.emitStmt(stmt);
            }
            ctx.indent--;
            ctx.blank();
        }

        // Always emit the entry point guard if there's a main function
        if (hasMainFn || !program.stmts().isEmpty()) {
            ctx.line("if __name__ == \"__main__\":");
            ctx.indent++;
            ctx.line("main()");
            ctx.indent--;
        }

        ctx.sb = savedSb;

        // Build final output: imports + body
        ctx.sb.append("# Generated by Zinc compiler — Python 3.14t target\n");
        ctx.sb.append("from __future__ import annotations\n");

        if (!ctx.fromImports.isEmpty()) {
            for (var imp : ctx.fromImports) {
                ctx.sb.append(imp).append("\n");
            }
        }
        if (!ctx.imports.isEmpty()) {
            for (var imp : ctx.imports) {
                ctx.sb.append("import ").append(imp).append("\n");
            }
        }
        if (!ctx.fromImports.isEmpty() || !ctx.imports.isEmpty()) {
            ctx.sb.append("\n");
        }

        ctx.sb.append(body);

        // Write file
        String moduleName = ctx.className.toLowerCase();
        try {
            Files.createDirectories(outDir);
        } catch (IOException e) {
            return Result.err("failed to create directory " + outDir + ": " + e.getMessage());
        }

        Path file = outDir.resolve(moduleName + ".py");
        try {
            Files.writeString(file, ctx.sb.toString());
        } catch (IOException e) {
            return Result.err("failed to write " + file + ": " + e.getMessage());
        }

        return Result.ok(file);
    }

    /**
     * Returns the Python source as a string without writing to disk.
     */
    public String render(Ast.Program program) {
        emit(program, Path.of("/dev/null"));
        return ctx.sb.toString();
    }

    /**
     * Returns the set of stdlib module names actually used by this compilation.
     * Call after emit() — scans fromImports for zinc_runtime references.
     */
    public Set<String> usedStdlibModules() {
        var used = new HashSet<String>();
        for (var imp : ctx.fromImports) {
            // Match: from .zinc_runtime import X, from ..zinc_runtime import X, etc.
            if (imp.matches("from \\.+\\w+ import .+")) {
                String modulePart = imp.replaceFirst("from \\.+", "").replaceFirst(" import .+", "");
                if (ZincStdlib.isPythonStdlibModule(modulePart)) {
                    used.add(modulePart + ".py");
                }
            }
        }
        return used;
    }
}
