// Copyright 2026 victorybhg
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

package zinc.compiler;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Emits Python 3.14t source from a Zinc AST.
 * Bypasses the Transformer (JavaParser) entirely — walks Ast.Program directly.
 */
public class PythonEmitter {

    private StringBuilder sb = new StringBuilder();
    private int indent = 0;
    private final Set<String> imports = new LinkedHashSet<>();
    private final Set<String> fromImports = new LinkedHashSet<>();
    private final String className;
    private final TargetRuntime target = new TargetRuntime.Python();
    private String currentClass = null;  // track which class we're inside
    private Set<String> currentClassFields = new HashSet<>();  // field names of current class
    private boolean insideMethod = false;  // track if we're inside a method body

    public PythonEmitter(String className) {
        this.className = className;
    }

    // --- Public API -----------------------------------------------------------

    /**
     * Emit a Zinc program as a single .py file.
     */
    public Result<Path> emit(Ast.Program program, Path outDir) {
        sb.setLength(0);
        imports.clear();
        fromImports.clear();

        // Resolve imports through target runtime
        for (var imp : program.imports()) {
            String resolved = target.resolveImport(imp.path());
            if (resolved != null) {
                addFromImport(resolved);
            }
        }

        // Collect body first (so imports accumulate)
        var body = new StringBuilder();
        var savedSb = sb;
        sb = body;

        // Emit all declarations
        for (var decl : program.decls()) {
            emitTopLevelDecl(decl);
            blank();
        }

        // Determine if there's an explicit main function
        boolean hasMainFn = program.decls().stream()
            .anyMatch(d -> d instanceof Ast.FnDecl fn && fn.name().equals("main"));

        // Script mode: top-level statements wrapped in main()
        if (!program.stmts().isEmpty() && !hasMainFn) {
            line("def main():");
            indent++;
            for (var stmt : program.stmts()) {
                emitStmt(stmt);
            }
            indent--;
            blank();
        }

        // Always emit the entry point guard if there's a main function
        if (hasMainFn || !program.stmts().isEmpty()) {
            line("if __name__ == \"__main__\":");
            indent++;
            line("main()");
            indent--;
        }

        sb = savedSb;

        // Build final output: imports + body
        sb.append("# Generated by Zinc compiler — Python 3.14t target\n");
        sb.append("from __future__ import annotations\n");

        if (!fromImports.isEmpty()) {
            for (var imp : fromImports) {
                sb.append(imp).append("\n");
            }
        }
        if (!imports.isEmpty()) {
            for (var imp : imports) {
                sb.append("import ").append(imp).append("\n");
            }
        }
        if (!fromImports.isEmpty() || !imports.isEmpty()) {
            sb.append("\n");
        }

        sb.append(body);

        // Write file — prefix with zn_ to avoid shadowing Python stdlib modules
        String moduleName = "zn_" + className.toLowerCase();
        try {
            Files.createDirectories(outDir);
        } catch (IOException e) {
            return Result.err("failed to create directory " + outDir + ": " + e.getMessage());
        }

        Path file = outDir.resolve(moduleName + ".py");
        try {
            Files.writeString(file, sb.toString());
        } catch (IOException e) {
            return Result.err("failed to write " + file + ": " + e.getMessage());
        }

        return Result.ok(file);
    }

    /**
     * Returns the Python source as a string without writing to disk.
     */
    public String render(Ast.Program program) {
        emit(program, Path.of("/dev/null"));
        return sb.toString();
    }

    // --- Top-level declarations ----------------------------------------------

    private void emitTopLevelDecl(Ast.TopLevelDecl decl) {
        switch (decl) {
            case Ast.FnDecl fn -> emitFnDecl(fn);
            case Ast.ClassDecl cls -> emitClassDecl(cls);
            case Ast.DataClassDecl data -> emitDataClassDecl(data);
            case Ast.SealedClassDecl sealed -> emitSealedClassDecl(sealed);
            case Ast.EnumDecl en -> emitEnumDecl(en);
            case Ast.InterfaceDecl iface -> emitInterfaceDecl(iface);
            case Ast.ConstDecl con -> emitConstDecl(con);
        }
    }

    // --- Functions -----------------------------------------------------------

    private void emitFnDecl(Ast.FnDecl fn) {
        for (var ann : fn.annotations()) {
            emitAnnotation(ann);
        }

        String retType = fn.returnType() != null ? emitType(fn.returnType()) : null;
        String params = emitParams(fn.params());

        if (fn.name().equals("main")) {
            line("def main(" + params + ")" + (retType != null ? " -> " + retType : "") + ":");
        } else {
            line("def " + fn.name() + "(" + params + ")" + (retType != null ? " -> " + retType : "") + ":");
        }

        indent++;

        // Single-expression function: body has one return statement
        if (fn.body() != null && fn.body().stmts().size() == 1
                && fn.body().stmts().getFirst() instanceof Ast.ReturnStmt ret) {
            line("return " + emitExpr(ret.value()));
        } else if (fn.body() != null && !fn.body().stmts().isEmpty()) {
            emitBlock(fn.body());
        } else {
            line("pass");
        }

        indent--;
    }

    // --- Classes -------------------------------------------------------------

    private void emitClassDecl(Ast.ClassDecl cls) {
        currentClass = cls.name();
        currentClassFields.clear();
        for (var field : cls.fields()) {
            currentClassFields.add(field.name());
        }
        for (var ann : cls.annotations()) {
            emitAnnotation(ann);
        }

        String parents = cls.parents().isEmpty() ? "" : "(" + String.join(", ", cls.parents()) + ")";
        line("class " + cls.name() + parents + ":");
        indent++;

        boolean hasContent = false;

        // Class-level constants
        for (var field : cls.fields()) {
            if (field.isConst()) {
                line(field.name() + " = " + emitExpr(field.defaultValue()));
                hasContent = true;
            }
        }

        // Constructors
        for (var ctor : cls.ctors()) {
            emitConstructor(cls, ctor);
            hasContent = true;
        }

        // If no constructor but has non-const fields, generate __init__
        if (cls.ctors().isEmpty() && cls.fields().stream().anyMatch(f -> !f.isConst())) {
            emitDefaultInit(cls);
            hasContent = true;
        }

        // Properties for pub/readonly fields
        for (var field : cls.fields()) {
            if (field.isConst()) continue;
            if (field.isPub() || field.isReadonly() || field.isInit()) {
                emitProperty(field);
                hasContent = true;
            }
        }

        // Methods
        for (var method : cls.methods()) {
            emitMethodDecl(method);
            hasContent = true;
        }

        if (!hasContent) {
            line("pass");
        }

        indent--;
        currentClass = null;
        currentClassFields.clear();
    }

    private void emitConstructor(Ast.ClassDecl cls, Ast.CtorDecl ctor) {
        String params = emitParams(ctor.params());
        line("def __init__(self" + (params.isEmpty() ? "" : ", " + params) + "):");
        indent++;

        // Super call
        if (!ctor.superArgs().isEmpty()) {
            var superArgsStr = ctor.superArgs().stream()
                .map(this::emitExpr).collect(java.util.stream.Collectors.joining(", "));
            line("super().__init__(" + superArgsStr + ")");
        }

        if (ctor.body() != null && !ctor.body().stmts().isEmpty()) {
            emitBlock(ctor.body());
        } else {
            line("pass");
        }

        indent--;
        blank();
    }

    private void emitDefaultInit(Ast.ClassDecl cls) {
        var nonConstFields = cls.fields().stream().filter(f -> !f.isConst()).toList();
        line("def __init__(self):");
        indent++;
        for (var field : nonConstFields) {
            String val = field.defaultValue() != null ? emitExpr(field.defaultValue()) : "None";
            line("self._" + field.name() + " = " + val);
        }
        indent--;
        blank();
    }

    private void emitProperty(Ast.FieldDecl field) {
        // Getter
        line("@property");
        line("def " + field.name() + "(self)" +
            (field.type() != null ? " -> " + emitType(field.type()) : "") + ":");
        indent++;
        line("return self._" + field.name());
        indent--;
        blank();

        // Setter (only for pub, not readonly/init)
        if (field.isPub() && !field.isReadonly() && !field.isInit()) {
            line("@" + field.name() + ".setter");
            line("def " + field.name() + "(self, value" +
                (field.type() != null ? ": " + emitType(field.type()) : "") + "):");
            indent++;
            line("self._" + field.name() + " = value");
            indent--;
            blank();
        }
    }

    // --- Data Classes --------------------------------------------------------

    private void emitDataClassDecl(Ast.DataClassDecl data) {
        addFromImport("from dataclasses import dataclass");

        String parents = data.parents().isEmpty() ? "" : "(" + String.join(", ", data.parents()) + ")";

        line("@dataclass(frozen=True, slots=True)");
        line("class " + data.name() + parents + ":");
        indent++;

        if (data.params().isEmpty() && data.methods().isEmpty()) {
            line("pass");
        } else {
            for (var param : data.params()) {
                String typeStr = param.type() != null ? emitType(param.type()) : "object";
                if (param.defaultValue() != null) {
                    line(param.name() + ": " + typeStr + " = " + emitExpr(param.defaultValue()));
                } else {
                    line(param.name() + ": " + typeStr);
                }
            }

            for (var method : data.methods()) {
                blank();
                emitMethodDecl(method);
            }
        }

        indent--;
    }

    // --- Sealed Classes ------------------------------------------------------

    private void emitSealedClassDecl(Ast.SealedClassDecl sealed) {
        // Base class
        String parents = sealed.parents().isEmpty() ? "" : "(" + String.join(", ", sealed.parents()) + ")";
        line("class " + sealed.name() + parents + ":");
        indent++;

        boolean hasContent = false;
        for (var method : sealed.methods()) {
            emitMethodDecl(method);
            hasContent = true;
        }
        if (!hasContent) {
            line("pass");
        }

        indent--;
        blank();

        // Variant data classes
        for (var variant : sealed.variants()) {
            addFromImport("from dataclasses import dataclass");
            line("@dataclass(frozen=True, slots=True)");
            line("class " + variant.name() + "(" + sealed.name() + "):");
            indent++;

            if (variant.params().isEmpty() && variant.methods().isEmpty()) {
                line("pass");
            } else {
                for (var param : variant.params()) {
                    String typeStr = param.type() != null ? emitType(param.type()) : "object";
                    if (param.defaultValue() != null) {
                        line(param.name() + ": " + typeStr + " = " + emitExpr(param.defaultValue()));
                    } else {
                        line(param.name() + ": " + typeStr);
                    }
                }
                for (var method : variant.methods()) {
                    blank();
                    emitMethodDecl(method);
                }
            }

            indent--;
            blank();
        }
    }

    // --- Enums ---------------------------------------------------------------

    private void emitEnumDecl(Ast.EnumDecl en) {
        addFromImport("from enum import Enum, auto");
        line("class " + en.name() + "(Enum):");
        indent++;
        for (var variant : en.variants()) {
            line(variant + " = auto()");
        }
        indent--;
    }

    // --- Interfaces ----------------------------------------------------------

    private void emitInterfaceDecl(Ast.InterfaceDecl iface) {
        addFromImport("from abc import ABC, abstractmethod");
        line("class " + iface.name() + "(ABC):");
        indent++;

        if (iface.methods().isEmpty()) {
            line("pass");
        } else {
            for (var sig : iface.methods()) {
                String params = emitParams(sig.params());
                String retType = sig.returnType() != null ? " -> " + emitType(sig.returnType()) : "";
                line("@abstractmethod");
                line("def " + sig.name() + "(self" + (params.isEmpty() ? "" : ", " + params) + ")" + retType + ":");
                indent++;
                line("pass");
                indent--;
                blank();
            }
        }

        indent--;
    }

    // --- Constants -----------------------------------------------------------

    private void emitConstDecl(Ast.ConstDecl con) {
        line(con.name() + " = " + emitExpr(con.value()));
    }

    // --- Methods -------------------------------------------------------------

    private void emitMethodDecl(Ast.MethodDecl method) {
        for (var ann : method.annotations()) {
            emitAnnotation(ann);
        }

        if (method.isStatic()) {
            line("@staticmethod");
        }

        String params = emitParams(method.params());
        String retType = method.returnType() != null ? " -> " + emitType(method.returnType()) : "";

        if (method.isStatic()) {
            line("def " + method.name() + "(" + params + ")" + retType + ":");
        } else {
            // Map fn init -> __init__, fn toString -> __str__/__repr__
            String pyName = switch (method.name()) {
                case "init" -> "__init__";
                case "toString" -> "__repr__";
                case "equals" -> "__eq__";
                case "hashCode" -> "__hash__";
                default -> method.name();
            };
            line("def " + pyName + "(self" + (params.isEmpty() ? "" : ", " + params) + ")" + retType + ":");
        }

        indent++;
        insideMethod = true;
        if (method.isAbstract() || method.body() == null || method.body().stmts().isEmpty()) {
            line("pass");
        } else {
            emitBlock(method.body());
        }
        insideMethod = false;
        indent--;
        blank();
    }

    // --- Statements ----------------------------------------------------------

    private void emitStmt(Ast.Stmt stmt) {
        switch (stmt) {
            case Ast.BlockStmt block -> emitBlock(block);
            case Ast.VarStmt var_ -> emitVarStmt(var_);
            case Ast.TupleVarStmt tv -> emitTupleVarStmt(tv);
            case Ast.AssignStmt assign -> emitAssignStmt(assign);
            case Ast.ReturnStmt ret -> emitReturnStmt(ret);
            case Ast.IfStmt if_ -> emitIfStmt(if_);
            case Ast.ForStmt for_ -> emitForStmt(for_);
            case Ast.WhileStmt while_ -> emitWhileStmt(while_);
            case Ast.MatchStmt match -> emitMatchStmt(match);
            case Ast.BreakStmt b -> line("break");
            case Ast.ContinueStmt c -> line("continue");
            case Ast.ExprStmt expr -> emitExprStmt(expr);
            case Ast.FnDecl fn -> emitFnDecl(fn);
            case Ast.WithStmt with -> emitWithStmt(with);
            case Ast.DeferStmt defer -> emitDeferStmt(defer);
            // Concurrency stubs — Phase 3
            case Ast.ParallelForStmt pf -> emitParallelForStmt(pf);
            case Ast.ConcurrentStmt cs -> emitConcurrentStmt(cs);
            case Ast.TimeoutStmt ts -> emitTimeoutStmt(ts);
        }
    }

    private void emitBlock(Ast.BlockStmt block) {
        if (block.stmts().isEmpty()) {
            line("pass");
            return;
        }
        for (var stmt : block.stmts()) {
            emitStmt(stmt);
        }
    }

    private void emitVarStmt(Ast.VarStmt var_) {
        String value = emitExpr(var_.value());

        if (var_.orHandler() != null) {
            emitOrWrapped(var_.name(), value, var_.orHandler());
            return;
        }

        if (var_.type() != null) {
            line(var_.name() + ": " + emitType(var_.type()) + " = " + value);
        } else {
            line(var_.name() + " = " + value);
        }
    }

    private void emitTupleVarStmt(Ast.TupleVarStmt tv) {
        String value = emitExpr(tv.value());
        if (tv.orHandler() != null) {
            String tmpName = "_tmp_" + tv.names().getFirst();
            emitOrWrapped(tmpName, value, tv.orHandler());
            // Unpack from tmp
            for (int i = 0; i < tv.names().size(); i++) {
                line(tv.names().get(i) + " = " + tmpName + "[" + i + "]");
            }
        } else {
            line(String.join(", ", tv.names()) + " = " + value);
        }
    }

    private void emitAssignStmt(Ast.AssignStmt assign) {
        String target = emitExpr(assign.target());
        String value = emitExpr(assign.value());

        // Handle this.x = y → self._x = y (inside class methods)
        if (assign.target() instanceof Ast.SelectorExpr sel
                && sel.object() instanceof Ast.ThisExpr) {
            target = "self._" + sel.field();
        }

        if (assign.orHandler() != null) {
            emitOrWrapped(target, value, assign.orHandler());
        } else {
            line(target + " " + assign.op() + " " + value);
        }
    }

    private void emitReturnStmt(Ast.ReturnStmt ret) {
        if (ret.value() == null) {
            line("return");
        } else if (ret.value() instanceof Ast.CallExpr call
                && call.callee() instanceof Ast.Ident id && id.name().equals("Error")) {
            // return Error("msg") → raise ZincError("msg")
            addFromImport("from zinc_runtime import ZincError");
            var args = call.args().stream().map(this::emitExpr)
                .collect(java.util.stream.Collectors.joining(", "));
            line("raise ZincError(" + args + ")");
        } else {
            line("return " + emitExpr(ret.value()));
        }
    }

    private void emitIfStmt(Ast.IfStmt if_) {
        line("if " + emitExpr(if_.cond()) + ":");
        indent++;
        emitBlock(if_.then());
        indent--;

        if (if_.elseStmt() != null) {
            if (if_.elseStmt() instanceof Ast.IfStmt elseIf) {
                // else if → elif
                raw("elif " + emitExpr(elseIf.cond()) + ":");
                indent++;
                emitBlock(elseIf.then());
                indent--;
                if (elseIf.elseStmt() != null) {
                    emitElseChain(elseIf.elseStmt());
                }
            } else if (if_.elseStmt() instanceof Ast.BlockStmt elseBlock) {
                line("else:");
                indent++;
                emitBlock(elseBlock);
                indent--;
            }
        }
    }

    private void emitElseChain(Ast.Stmt elseStmt) {
        if (elseStmt instanceof Ast.IfStmt elseIf) {
            raw("elif " + emitExpr(elseIf.cond()) + ":");
            indent++;
            emitBlock(elseIf.then());
            indent--;
            if (elseIf.elseStmt() != null) {
                emitElseChain(elseIf.elseStmt());
            }
        } else if (elseStmt instanceof Ast.BlockStmt elseBlock) {
            line("else:");
            indent++;
            emitBlock(elseBlock);
            indent--;
        }
    }

    private void emitForStmt(Ast.ForStmt for_) {
        if (for_.isRange()) {
            String item = for_.item();
            String rangeExpr = emitExpr(for_.range());

            if (for_.indexVar() != null && !for_.indexVar().isEmpty()) {
                // for i, x in items → for i, x in enumerate(items)
                // for key, value in map → for key, value in map.items()
                if (for_.range() instanceof Ast.Ident) {
                    // Could be a map — emit .items() for Map types
                    line("for " + for_.indexVar() + ", " + item + " in " + rangeExpr + ".items():");
                } else {
                    line("for " + for_.indexVar() + ", " + item + " in enumerate(" + rangeExpr + "):");
                }
            } else if (for_.range() instanceof Ast.RangeExpr range) {
                // for i in 0..10 → for i in range(0, 10)
                // for i in 1..=10 → for i in range(1, 11)
                String start = emitExpr(range.start());
                String end = emitExpr(range.end());
                if (range.inclusive()) {
                    line("for " + item + " in range(" + start + ", " + end + " + 1):");
                } else {
                    line("for " + item + " in range(" + start + ", " + end + "):");
                }
            } else {
                line("for " + item + " in " + rangeExpr + ":");
            }
        } else {
            // C-style for loop → while loop
            if (for_.init() != null) emitStmt(for_.init());
            line("while " + (for_.cond() != null ? emitExpr(for_.cond()) : "True") + ":");
            indent++;
            emitBlock(for_.body());
            if (for_.post() != null) emitStmt(for_.post());
            indent--;
            return;
        }

        indent++;
        emitBlock(for_.body());
        indent--;
    }

    private void emitWhileStmt(Ast.WhileStmt while_) {
        line("while " + emitExpr(while_.cond()) + ":");
        indent++;
        emitBlock(while_.body());
        indent--;
    }

    private void emitMatchStmt(Ast.MatchStmt match) {
        line("match " + emitExpr(match.subject()) + ":");
        indent++;
        for (var case_ : match.cases()) {
            emitMatchCase(case_);
        }
        indent--;
    }

    private void emitMatchCase(Ast.MatchCase case_) {
        String pattern = emitMatchPattern(case_.pattern());
        line("case " + pattern + ":");
        indent++;
        emitBlock(case_.body());
        indent--;
    }

    private String emitMatchPattern(Ast.Expr pattern) {
        if (pattern == null) return "_";
        return switch (pattern) {
            case Ast.Ident id -> {
                if (id.name().equals("_")) yield "_";
                yield id.name();
            }
            case Ast.StringLit s -> "\"" + s.value() + "\"";
            case Ast.IntLit i -> i.value();
            case Ast.BoolLit b -> b.value() ? "True" : "False";
            case Ast.NullLit n -> "None";
            // Type pattern: case Circle(r) → case Circle(r=r)
            case Ast.CallExpr call -> {
                String callee = emitExpr(call.callee());
                if (call.args().isEmpty()) {
                    yield callee + "()";
                }
                var args = call.args().stream()
                    .map(this::emitExpr)
                    .collect(java.util.stream.Collectors.joining(", "));
                yield callee + "(" + args + ")";
            }
            default -> emitExpr(pattern);
        };
    }

    private void emitExprStmt(Ast.ExprStmt expr) {
        if (expr.orHandler() != null) {
            emitOrWrapped(null, emitExpr(expr.expr()), expr.orHandler());
        } else {
            line(emitExpr(expr.expr()));
        }
    }

    private void emitWithStmt(Ast.WithStmt with) {
        // with f = open("file") { } → with open("file") as f:
        var parts = new ArrayList<String>();
        for (var res : with.resources()) {
            parts.add(emitExpr(res.value()) + " as " + res.name());
        }
        line("with " + String.join(", ", parts) + ":");
        indent++;
        emitBlock(with.body());
        indent--;
    }

    private void emitDeferStmt(Ast.DeferStmt defer) {
        // defer → atexit.register or try/finally pattern
        // For now emit as a comment + atexit
        addImport("atexit");
        line("atexit.register(lambda: " + emitExpr(defer.expr()) + ")");
    }

    // --- Concurrency (Phase 3 stubs) -----------------------------------------

    private void emitParallelForStmt(Ast.ParallelForStmt pf) {
        addFromImport("from concurrent.futures import ThreadPoolExecutor");
        int max = pf.max() > 0 ? pf.max() : 0;
        String maxWorkers = max > 0 ? "max_workers=" + max : "";
        line("with ThreadPoolExecutor(" + maxWorkers + ") as _executor:");
        indent++;
        line("list(_executor.map(lambda " + pf.item() + ": (lambda: None)(), " + emitExpr(pf.range()) + "))");
        // TODO: Phase 3 — proper structured scope with ZincScope
        indent--;
    }

    private void emitConcurrentStmt(Ast.ConcurrentStmt cs) {
        addFromImport("from concurrent.futures import ThreadPoolExecutor, wait");
        line("with ThreadPoolExecutor() as _executor:");
        indent++;
        line("_futures = []");
        for (var task : cs.tasks()) {
            line("_futures.append(_executor.submit(lambda: " + emitExpr(task) + "))");
        }
        line("wait(_futures)");
        if (!cs.names().isEmpty()) {
            for (int i = 0; i < cs.names().size(); i++) {
                line(cs.names().get(i) + " = _futures[" + i + "].result()");
            }
        }
        indent--;
    }

    private void emitTimeoutStmt(Ast.TimeoutStmt ts) {
        // Stub: timeout as a comment for now
        line("# TODO: timeout(" + emitExpr(ts.duration()) + ")");
        indent++;
        emitBlock(ts.body());
        indent--;
    }

    // --- Or handler ----------------------------------------------------------

    private void emitOrWrapped(String target, String value, Ast.OrHandler handler) {
        line("try:");
        indent++;
        if (target != null) {
            line(target + " = " + value);
        } else {
            line(value);
        }
        indent--;

        if (handler.matchCases() != null && !handler.matchCases().isEmpty()) {
            for (var mc : handler.matchCases()) {
                line("except " + mc.type() + " as err:");
                indent++;
                emitBlock(mc.body());
                indent--;
            }
        } else {
            line("except Exception as err:");
            indent++;
            if (handler.body() != null && !handler.body().stmts().isEmpty()) {
                // Check if the body is a single expression (the fallback value)
                // e.g., `divide(10, 0) or -1` → body is just the expr `-1`
                var stmts = handler.body().stmts();
                if (target != null && stmts.size() == 1 && stmts.getFirst() instanceof Ast.ExprStmt expr
                        && expr.orHandler() == null) {
                    // Simple fallback: assign the expression as the default value
                    line(target + " = " + emitExpr(expr.expr()));
                } else {
                    emitBlock(handler.body());
                }
            } else {
                if (target != null) {
                    line(target + " = None");
                } else {
                    line("pass");
                }
            }
            indent--;
        }
    }

    // --- Expressions ---------------------------------------------------------

    private String emitExpr(Ast.Expr expr) {
        if (expr == null) return "None";
        return switch (expr) {
            case Ast.IntLit i -> i.value();
            case Ast.FloatLit f -> f.value();
            case Ast.StringLit s -> "\"" + escapeString(s.value()) + "\"";
            case Ast.StringInterpLit interp -> emitStringInterp(interp);
            case Ast.RawStringLit r -> "r\"" + r.value() + "\"";
            case Ast.BoolLit b -> b.value() ? "True" : "False";
            case Ast.NullLit n -> "None";
            case Ast.Ident id -> emitIdent(id);
            case Ast.ThisExpr t -> "self";
            case Ast.BinaryExpr bin -> emitBinaryExpr(bin);
            case Ast.UnaryExpr un -> emitUnaryExpr(un);
            case Ast.CallExpr call -> emitCallExpr(call);
            case Ast.SelectorExpr sel -> emitSelectorExpr(sel);
            case Ast.SafeNavExpr safe -> emitSafeNavExpr(safe);
            case Ast.IndexExpr idx -> emitExpr(idx.object()) + "[" + emitExpr(idx.index()) + "]";
            case Ast.SliceExpr sl -> emitExpr(sl.object()) + "[" + emitExpr(sl.low()) + ":" + emitExpr(sl.high()) + "]";
            case Ast.ListLit list -> emitListLit(list);
            case Ast.MapLit map -> emitMapLit(map);
            case Ast.LambdaExpr lam -> emitLambdaExpr(lam);
            case Ast.SpawnExpr spawn -> emitSpawnExpr(spawn);
            case Ast.IfExpr ife -> emitIfExpr(ife);
            case Ast.MatchExpr me -> emitMatchExpr(me);
            case Ast.RangeExpr range -> emitRangeExpr(range);
            case Ast.TupleLit tuple -> "(" + tuple.elements().stream().map(this::emitExpr).collect(java.util.stream.Collectors.joining(", ")) + (tuple.elements().size() == 1 ? ",)" : ")");
            case Ast.SpreadExpr spread -> "*" + emitExpr(spread.expr());
            case Ast.TypeAssertExpr ta -> emitTypeAssert(ta);
            case Ast.SuperCallExpr sup -> {
                var args = sup.args().stream().map(this::emitExpr).collect(java.util.stream.Collectors.joining(", "));
                yield "super().__init__(" + args + ")";
            }
        };
    }

    private String emitIdent(Ast.Ident id) {
        return switch (id.name()) {
            case "print" -> "print";
            case "null" -> "None";
            case "true" -> "True";
            case "false" -> "False";
            default -> {
                // Inside a class method, bare field references → self._field
                if (insideMethod && currentClassFields.contains(id.name())) {
                    yield "self._" + id.name();
                }
                yield id.name();
            }
        };
    }

    private String emitBinaryExpr(Ast.BinaryExpr bin) {
        String left = emitExpr(bin.left());
        String right = emitExpr(bin.right());
        String op = switch (bin.op()) {
            case "&&" -> "and";
            case "||" -> "or";
            case "===" -> "is";
            case "!==" -> "is not";
            case "**" -> "**";
            case "/" -> "//";  // Zinc int division → Python floor division
            case "is" -> {
                yield null; // handled below
            }
            case "is not" -> {
                yield null; // handled below
            }
            case "in" -> "in";
            case "not in" -> "not in";
            default -> bin.op();
        };

        // Special case: type checks
        if (bin.op().equals("is")) {
            return "isinstance(" + left + ", " + mapTypeName(right) + ")";
        }
        if (bin.op().equals("is not")) {
            return "not isinstance(" + left + ", " + mapTypeName(right) + ")";
        }

        return "(" + left + " " + op + " " + right + ")";
    }

    private String emitUnaryExpr(Ast.UnaryExpr un) {
        String operand = emitExpr(un.operand());
        return switch (un.op()) {
            case "!" -> "not " + operand;
            case "not" -> "not " + operand;
            case "-" -> "(-" + operand + ")";
            default -> un.op() + operand;
        };
    }

    private String emitCallExpr(Ast.CallExpr call) {
        // Handle new Foo(args) → Foo(args)
        String callee = emitExpr(call.callee());

        // Map known Java methods to Python
        if (call.callee() instanceof Ast.SelectorExpr sel) {
            String obj = emitExpr(sel.object());
            String method = sel.field();
            String mapped = mapMethodCall(obj, method, call.args());
            if (mapped != null) return mapped;

            // Map Java static calls to Python equivalents
            String fullCall = obj + "." + method;
            String staticMapped = mapStaticCall(fullCall, call.args());
            if (staticMapped != null) return staticMapped;
        }

        // Map top-level Java calls
        if (call.callee() instanceof Ast.Ident id) {
            // Inside a method, bare getter calls → self.property
            if (insideMethod && id.name().startsWith("get") && id.name().length() > 3
                    && call.args().isEmpty()) {
                String fieldName = Character.toLowerCase(id.name().charAt(3)) + id.name().substring(4);
                return "self." + fieldName;
            }

            // Handle known static methods without an object
            String mapped = mapStaticCall(id.name(), call.args());
            if (mapped != null) return mapped;
        }

        var args = new ArrayList<String>();
        for (var arg : call.args()) {
            args.add(emitExpr(arg));
        }
        for (var named : call.namedArgs()) {
            args.add(named.name() + "=" + emitExpr(named.value()));
        }

        return callee + "(" + String.join(", ", args) + ")";
    }

    /**
     * Map Java static method calls to Python equivalents.
     */
    private String mapStaticCall(String fullName, List<Ast.Expr> args) {
        return switch (fullName) {
            // Set.of(...) → {...}
            case "Set.of" -> {
                var elements = args.stream().map(this::emitExpr)
                    .collect(java.util.stream.Collectors.joining(", "));
                yield "{" + elements + "}";
            }
            // List.of(...) → [...]
            case "List.of" -> {
                var elements = args.stream().map(this::emitExpr)
                    .collect(java.util.stream.Collectors.joining(", "));
                yield "[" + elements + "]";
            }
            // Map.of(k1, v1, k2, v2) → {k1: v1, k2: v2}
            case "Map.of" -> {
                var entries = new ArrayList<String>();
                for (int i = 0; i + 1 < args.size(); i += 2) {
                    entries.add(emitExpr(args.get(i)) + ": " + emitExpr(args.get(i + 1)));
                }
                yield "{" + String.join(", ", entries) + "}";
            }
            // Math methods
            case "Math.sqrt" -> "math.sqrt(" + emitExpr(args.getFirst()) + ")";
            case "Math.abs" -> "abs(" + emitExpr(args.getFirst()) + ")";
            case "Math.max" -> "max(" + emitExpr(args.get(0)) + ", " + emitExpr(args.get(1)) + ")";
            case "Math.min" -> "min(" + emitExpr(args.get(0)) + ", " + emitExpr(args.get(1)) + ")";
            case "Math.PI" -> "math.pi";
            // String.valueOf → str()
            case "String.valueOf" -> "str(" + emitExpr(args.getFirst()) + ")";
            // Integer.parseInt → int()
            case "Integer.parseInt" -> "int(" + emitExpr(args.getFirst()) + ")";
            case "Double.parseDouble" -> "float(" + emitExpr(args.getFirst()) + ")";
            // Arrays.toString → str()
            case "java.util.Arrays.toString" -> "str(" + emitExpr(args.getFirst()) + ")";
            default -> null;
        };
    }

    /**
     * Map Zinc/Java collection methods to Python equivalents.
     * Returns null if no mapping exists (use default call emission).
     */
    private String mapMethodCall(String obj, String method, List<Ast.Expr> args) {
        return switch (method) {
            // Collection methods
            case "size" -> "len(" + obj + ")";
            case "isEmpty" -> "(len(" + obj + ") == 0)";
            case "contains" -> "(" + emitExpr(args.getFirst()) + " in " + obj + ")";
            case "add" -> obj + ".append(" + emitExpr(args.getFirst()) + ")";
            case "addAll" -> obj + ".extend(" + emitExpr(args.getFirst()) + ")";
            case "get" -> obj + "[" + emitExpr(args.getFirst()) + "]";
            case "set" -> {
                yield obj + "[" + emitExpr(args.get(0)) + "] = " + emitExpr(args.get(1));
            }
            case "remove" -> obj + ".remove(" + emitExpr(args.getFirst()) + ")";
            case "removeLast" -> obj + ".pop()";

            // Functional collection methods → list comprehensions / builtins
            case "filter" -> {
                String pred = emitExpr(args.getFirst());
                yield "[_x for _x in " + obj + " if " + applyLambda(pred, "_x") + "]";
            }
            case "map" -> {
                String fn = emitExpr(args.getFirst());
                yield "[" + applyLambda(fn, "_x") + " for _x in " + obj + "]";
            }
            case "forEach" -> {
                String fn = emitExpr(args.getFirst());
                yield "[" + applyLambda(fn, "_x") + " for _x in " + obj + "]";
            }
            case "sum" -> "sum(" + obj + ")";
            case "min" -> "min(" + obj + ")";
            case "max" -> "max(" + obj + ")";
            case "count" -> "len(" + obj + ")";
            case "distinct" -> "list(dict.fromkeys(" + obj + "))";
            case "toList" -> "list(" + obj + ")";
            case "toSet" -> "set(" + obj + ")";
            case "sortBy" -> {
                String key = emitExpr(args.getFirst());
                yield "sorted(" + obj + ", key=lambda _x: " + applyLambda(key, "_x") + ")";
            }
            case "reduce" -> {
                addImport("functools");
                yield "functools.reduce(" + emitExpr(args.get(1)) + ", " + obj + ", " + emitExpr(args.get(0)) + ")";
            }
            case "anyMatch" -> "any(" + applyLambda(emitExpr(args.getFirst()), "_x") + " for _x in " + obj + ")";
            case "allMatch" -> "all(" + applyLambda(emitExpr(args.getFirst()), "_x") + " for _x in " + obj + ")";
            case "findFirst" -> {
                if (args.isEmpty()) {
                    yield "next(iter(" + obj + "), None)";
                }
                String pred = emitExpr(args.getFirst());
                yield "next((_x for _x in " + obj + " if " + applyLambda(pred, "_x") + "), None)";
            }
            case "limit" -> obj + "[:" + emitExpr(args.getFirst()) + "]";
            case "skip" -> obj + "[" + emitExpr(args.getFirst()) + ":]";
            case "groupBy" -> {
                addImport("itertools");
                String key = emitExpr(args.getFirst());
                yield "{k: list(v) for k, v in itertools.groupby(sorted(" + obj + ", key=lambda _x: " + applyLambda(key, "_x") + "), key=lambda _x: " + applyLambda(key, "_x") + ")}";
            }

            // String methods
            case "toUpperCase", "upper" -> obj + ".upper()";
            case "toLowerCase", "lower" -> obj + ".lower()";
            case "trim" -> obj + ".strip()";
            case "trimStart", "stripLeading" -> obj + ".lstrip()";
            case "trimEnd", "stripTrailing" -> obj + ".rstrip()";
            case "startsWith" -> obj + ".startswith(" + emitExpr(args.getFirst()) + ")";
            case "endsWith" -> obj + ".endswith(" + emitExpr(args.getFirst()) + ")";
            case "length" -> "len(" + obj + ")";
            case "charAt" -> obj + "[" + emitExpr(args.getFirst()) + "]";
            case "indexOf" -> obj + ".find(" + emitExpr(args.getFirst()) + ")";
            case "substring" -> {
                if (args.size() == 1) yield obj + "[" + emitExpr(args.getFirst()) + ":]";
                yield obj + "[" + emitExpr(args.get(0)) + ":" + emitExpr(args.get(1)) + "]";
            }
            case "split" -> obj + ".split(" + emitExpr(args.getFirst()) + ")";
            case "replace" -> obj + ".replace(" + emitExpr(args.get(0)) + ", " + emitExpr(args.get(1)) + ")";
            case "repeat" -> "(" + obj + " * " + emitExpr(args.getFirst()) + ")";
            case "isBlank" -> "(len(" + obj + ".strip()) == 0)";
            case "toString" -> "str(" + obj + ")";

            // Map methods
            case "put" -> {
                yield obj + "[" + emitExpr(args.get(0)) + "] = " + emitExpr(args.get(1));
            }
            case "containsKey" -> "(" + emitExpr(args.getFirst()) + " in " + obj + ")";
            case "getOrDefault" -> obj + ".get(" + emitExpr(args.get(0)) + ", " + emitExpr(args.get(1)) + ")";
            case "entrySet" -> obj + ".items()";
            case "keySet" -> obj + ".keys()";
            case "values" -> obj + ".values()";

            // Map.Entry methods (entry.getKey() → key, entry.getValue() → value)
            case "getKey" -> obj + "[0]";
            case "getValue" -> obj + "[1]";

            // Getter methods generated by Zinc → direct attribute access in Python
            default -> {
                if (method.startsWith("get") && method.length() > 3 && args.isEmpty()) {
                    // getFoo() → .foo (property access)
                    String fieldName = Character.toLowerCase(method.charAt(3)) + method.substring(4);
                    yield obj + "." + fieldName;
                }
                yield null;
            }
        };
    }

    /**
     * Apply a lambda to a variable, inlining when possible.
     * "lambda x: x * 2" with varName "_x" → "(_x * 2)" (inline the body).
     * Falls back to calling the lambda if parsing fails.
     */
    private String applyLambda(String lambdaStr, String varName) {
        // Try to inline: "lambda x: BODY" → substitute x with varName in BODY
        if (lambdaStr.startsWith("lambda ")) {
            int colonIdx = lambdaStr.indexOf(": ");
            if (colonIdx > 0) {
                String paramPart = lambdaStr.substring(7, colonIdx).strip();
                String body = lambdaStr.substring(colonIdx + 2);
                // Single-param lambda: inline by replacing param with varName
                if (!paramPart.contains(",")) {
                    String param = paramPart.strip();
                    // Word-boundary replacement to avoid replacing substrings
                    return body.replaceAll("\\b" + java.util.regex.Pattern.quote(param) + "\\b", varName);
                }
            }
        }
        return lambdaStr + "(" + varName + ")";
    }

    private String emitSelectorExpr(Ast.SelectorExpr sel) {
        String obj = emitExpr(sel.object());

        // this.field → self._field
        if (sel.object() instanceof Ast.ThisExpr) {
            return "self._" + sel.field();
        }

        // .length on arrays → len()
        if (sel.field().equals("length")) {
            return "len(" + obj + ")";
        }

        // .class → type reference (for reflection)
        if (sel.field().equals("class")) {
            return obj;
        }

        // Math.PI → math.pi
        if (obj.equals("Math") && sel.field().equals("PI")) {
            addImport("math");
            return "math.pi";
        }
        if (obj.equals("Math") && sel.field().equals("E")) {
            addImport("math");
            return "math.e";
        }

        return obj + "." + sel.field();
    }

    private String emitSafeNavExpr(Ast.SafeNavExpr safe) {
        String obj = emitExpr(safe.object());
        if (safe.call() != null) {
            var args = safe.call().args().stream().map(this::emitExpr)
                .collect(java.util.stream.Collectors.joining(", "));
            return "(" + obj + "." + safe.field() + "(" + args + ") if " + obj + " is not None else None)";
        }
        return "(" + obj + "." + safe.field() + " if " + obj + " is not None else None)";
    }

    private String emitListLit(Ast.ListLit list) {
        var elements = list.elements().stream()
            .map(this::emitExpr)
            .collect(java.util.stream.Collectors.joining(", "));
        return "[" + elements + "]";
    }

    private String emitMapLit(Ast.MapLit map) {
        if (map.keys().isEmpty()) return "{}";
        var entries = new ArrayList<String>();
        for (int i = 0; i < map.keys().size(); i++) {
            entries.add(emitExpr(map.keys().get(i)) + ": " + emitExpr(map.values().get(i)));
        }
        return "{" + String.join(", ", entries) + "}";
    }

    private int lambdaCounter = 0;

    private String emitLambdaExpr(Ast.LambdaExpr lam) {
        var params = lam.params().stream()
            .map(Ast.ParamDecl::name)
            .collect(java.util.stream.Collectors.joining(", "));

        // Single-expression lambda
        if (lam.body().stmts().size() == 1) {
            var stmt = lam.body().stmts().getFirst();
            if (stmt instanceof Ast.ReturnStmt ret) {
                return "lambda " + params + ": " + emitExpr(ret.value());
            }
            if (stmt instanceof Ast.ExprStmt expr) {
                return "lambda " + params + ": " + emitExpr(expr.expr());
            }
        }

        // Multi-statement lambda → emit a named inner function before this line
        // Python lambdas must be single-expression, so we hoist the block
        String fnName = "_lambda_" + (lambdaCounter++);
        line("def " + fnName + "(" + params + "):");
        indent++;
        emitBlock(lam.body());
        indent--;

        // Return the function name — it will be used as a callable
        return fnName;
    }

    private String emitSpawnExpr(Ast.SpawnExpr spawn) {
        addFromImport("from concurrent.futures import ThreadPoolExecutor");
        // Simplified: spawn → submit to thread pool
        return "_executor.submit(lambda: None)  # TODO: spawn block";
    }

    private String emitIfExpr(Ast.IfExpr ife) {
        return "(" + emitExpr(ife.then()) + " if " + emitExpr(ife.cond()) + " else " + emitExpr(ife.elseExpr()) + ")";
    }

    private String emitMatchExpr(Ast.MatchExpr me) {
        // Python doesn't have match expressions that return values inline
        // Use a series of conditional expressions
        if (me.cases().isEmpty()) return "None";

        var result = new StringBuilder();
        for (int i = 0; i < me.cases().size(); i++) {
            var case_ = me.cases().get(i);
            String value = emitExpr(case_.value());
            String pattern = emitExpr(case_.pattern());

            if (pattern.equals("_") || i == me.cases().size() - 1) {
                result.append(value);
                break;
            }
            result.append("(").append(value).append(" if ")
                .append(emitExpr(me.subject())).append(" == ").append(pattern)
                .append(" else ");
        }

        // Close parentheses
        long openParens = result.chars().filter(c -> c == '(').count();
        long closeParens = result.chars().filter(c -> c == ')').count();
        for (long i = closeParens; i < openParens; i++) {
            result.append(")");
        }

        return result.toString();
    }

    private String emitRangeExpr(Ast.RangeExpr range) {
        String start = emitExpr(range.start());
        String end = emitExpr(range.end());
        if (range.inclusive()) {
            return "range(" + start + ", " + end + " + 1)";
        }
        return "range(" + start + ", " + end + ")";
    }

    private String emitTypeAssert(Ast.TypeAssertExpr ta) {
        String obj = emitExpr(ta.object());
        String type = mapTypeName(ta.typeName());
        if (ta.isCheck()) {
            return "isinstance(" + obj + ", " + type + ")";
        }
        // as → cast (Python doesn't need explicit casts, but we type-hint)
        return obj;
    }

    private String emitStringInterp(Ast.StringInterpLit interp) {
        var sb = new StringBuilder("f\"");
        for (var part : interp.parts()) {
            if (part instanceof Ast.StringLit s) {
                sb.append(escapeString(s.value()));
            } else {
                sb.append("{").append(emitExpr(part)).append("}");
            }
        }
        sb.append("\"");
        return sb.toString();
    }

    // --- Types ---------------------------------------------------------------

    private String emitType(Ast.TypeExpr type) {
        return switch (type) {
            case Ast.SimpleType s -> mapTypeName(s.name());
            case Ast.GenericType g -> {
                String name = mapTypeName(g.name());
                var args = g.typeArgs().stream()
                    .map(this::emitType)
                    .collect(java.util.stream.Collectors.joining(", "));
                yield name + "[" + args + "]";
            }
            case Ast.OptionalType o -> emitType(o.inner()) + " | None";
            case Ast.ArrayType a -> "list[" + emitType(a.elementType()) + "]";
            case Ast.FuncType f -> {
                addFromImport("from collections.abc import Callable");
                var params = f.params().stream()
                    .map(this::emitType)
                    .collect(java.util.stream.Collectors.joining(", "));
                String ret = f.returnType() != null ? emitType(f.returnType()) : "None";
                yield "Callable[[" + params + "], " + ret + "]";
            }
        };
    }

    private String mapTypeName(String name) {
        return switch (name) {
            case "int", "Integer" -> "int";
            case "double", "Double", "float", "Float" -> "float";
            case "boolean", "Boolean" -> "bool";
            case "String" -> "str";
            case "byte[]" -> "bytes";
            case "void" -> "None";
            case "any", "Object" -> "object";
            case "List" -> "list";
            case "Map" -> "dict";
            case "Set" -> "set";
            default -> name;
        };
    }

    // --- Parameters ----------------------------------------------------------

    private String emitParams(List<Ast.ParamDecl> params) {
        var parts = new ArrayList<String>();
        for (var p : params) {
            String part = p.name();
            if (p.type() != null) {
                part += ": " + emitType(p.type());
            }
            if (p.isVariadic()) {
                part = "*" + part;
            }
            if (p.defaultValue() != null) {
                part += " = " + emitExpr(p.defaultValue());
            }
            parts.add(part);
        }
        return String.join(", ", parts);
    }

    // --- Annotations ---------------------------------------------------------

    private void emitAnnotation(Ast.Annotation ann) {
        // Map Java annotations to Python decorators where applicable
        switch (ann.name()) {
            case "Override" -> {} // Python doesn't need this
            case "Deprecated" -> line("# @deprecated");
            default -> line("# @" + ann.name() + (ann.args().isEmpty() ? "" : "(" + String.join(", ", ann.args()) + ")"));
        }
    }

    // --- Helpers -------------------------------------------------------------

    private void line(String s) {
        sb.append("    ".repeat(indent)).append(s).append("\n");
    }

    /** Like line() but doesn't add a newline prefix — used for elif/else continuation */
    private void raw(String s) {
        sb.append("    ".repeat(indent)).append(s).append("\n");
    }

    private void blank() {
        sb.append("\n");
    }

    private void addImport(String module) {
        imports.add(module);
    }

    private void addFromImport(String stmt) {
        fromImports.add(stmt);
    }

    private static String escapeString(String s) {
        return s.replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\t", "\\t");
    }
}
