import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/** zc — the zinc meta-builder for BEAM (patterned on compilers/zinc-go cmd/zinc). */
public class Zc {
  static Path home; // beam-transpiler root (transpiler + rebar_zinc plugin live here)

  public static void main(String[] args) throws Exception {
    String h = System.getProperty("zinc.home", System.getenv("ZINC_HOME"));
    if (h == null) die("zc: ZINC_HOME not set (run via bin/zc)");
    home = Path.of(h).toAbsolutePath();
    if (args.length == 0) {
      usage();
      System.exit(1);
    }
    switch (args[0]) {
      case "init", "new" -> {
        if (args.length < 2) die("usage: zc init <name>");
        init(args[1]);
      }
      case "build" -> build(projectDir(args));
      case "run" -> {
        Path dir = projectDir(args);
        build(dir);
        run(dir);
      }
      case "clean" -> {
        Path dir = projectDir(args);
        ensureGenerated(dir, loadToml(dir));
        exec(dir, "rebar3", "clean");
      }
      case "deps" -> {
        var cfg = loadToml(projectDir(args));
        cfg.getOrDefault("deps", Map.of()).forEach((k, v) -> System.out.println(k + " " + v));
      }
      case "add" -> {
        if (args.length < 2) die("usage: zc add <name@version>  (hex package)");
        add(projectDir(new String[] {""}), args[1]);
      }
      case "fmt" -> die("zc fmt: not implemented yet");
      case "version", "--version", "-v" -> System.out.println("zc 0.1.0 (zinc on BEAM)");
      default -> {
        usage();
        System.exit(1);
      }
    }
  }

  static Path projectDir(String[] args) {
    Path dir = Path.of(args.length >= 2 && !args[1].startsWith("-") ? args[1] : ".");
    if (!Files.exists(dir.resolve("zinc.toml"))) {
      die("zc: no zinc.toml in " + dir.toAbsolutePath() + " (use 'zc init <name>')");
    }
    return dir;
  }

  // ---- init ----

  static void init(String name) throws IOException {
    Path dir = Path.of(name);
    if (Files.exists(dir)) die("zc: directory '" + name + "' already exists");
    Files.createDirectories(dir.resolve("src"));
    String base = dir.getFileName().toString();
    Files.writeString(dir.resolve("zinc.toml"), """
        [project]
        name = "%s"
        version = "0.1.0"

        [otp]
        version = "29"

        [deps]
        # hex packages, e.g.:  cowboy = "2.12.0"
        """.formatted(base));
    Files.writeString(dir.resolve("src/Main.zinc"), """
        public class Main {
          public static void main(String[] args) {
            System.out.println("Hello from %s!");
          }
        }
        """.formatted(base));
    Files.writeString(dir.resolve(".gitignore"),
        "_build/\n_checkouts/\nsrc/zinc_gen/\nrebar.config\nsrc/*.app.src\n");
    ensureGenerated(dir, loadToml(dir));
    System.out.println("created " + name + "/");
    System.out.println("  zinc.toml  src/Main.zinc");
    System.out.println("next: cd " + name + " && zc run");
  }

  // ---- generated build files (rebar.config, .app.src) -- regenerated every build ----

  static void ensureGenerated(Path dir, Map<String, Map<String, String>> cfg) throws IOException {
    var project = cfg.getOrDefault("project", Map.of());
    String name = project.getOrDefault("name", dir.toAbsolutePath().getFileName().toString());
    String vsn = project.getOrDefault("version", "0.1.0");
    var deps = cfg.getOrDefault("deps", Map.of());

    var depList = new ArrayList<String>();
    var depApps = new ArrayList<String>();
    deps.forEach((k, v) -> {
      depList.add("{" + k + ", \"" + v + "\"}");
      depApps.add(", " + k);
    });
    Files.writeString(dir.resolve("rebar.config"), """
        %% generated by zc from zinc.toml -- do not edit
        {plugins, [rebar_zinc]}.
        {provider_hooks, [{pre, [{compile, {zinc, compile}}]},
                          {post, [{clean, {zinc, clean}}]}]}.
        {src_dirs, [{"src", [{recursive, true}]}]}.
        {deps, [%s]}.
        """.formatted(String.join(", ", depList)));
    Files.writeString(dir.resolve("src/" + name + ".app.src"), """
        %% generated by zc from zinc.toml -- do not edit
        {application, %s, [
            {description, "%s"},
            {vsn, "%s"},
            {registered, []},
            {applications, [kernel, stdlib%s]},
            {env, []},
            {modules, []}
        ]}.
        """.formatted(name, name, vsn, String.join("", depApps)));
    // the rebar_zinc plugin resolves from _checkouts until it's published
    Path checkouts = dir.resolve("_checkouts");
    Files.createDirectories(checkouts);
    Path link = checkouts.resolve("rebar_zinc");
    if (!Files.exists(link, LinkOption.NOFOLLOW_LINKS)) {
      Files.createSymbolicLink(link, home.resolve("rebar_zinc"));
    }
  }

  // ---- hex deps: zc fetches and vendors into _checkouts; rebar3 then builds offline.
  // (rebar3's own fetch uses Erlang TLS, which fingerprint-filtering egress fireworks drop;
  // zc's Java TLS passes. Vendoring also serves hermetic/reproducible builds.)

  static void vendorDeps(Path dir, Map<String, Map<String, String>> cfg) throws Exception {
    var queue = new LinkedHashMap<String, String>(cfg.getOrDefault("deps", Map.of()));
    var seen = new HashSet<String>();
    while (!queue.isEmpty()) {
      var it = queue.entrySet().iterator();
      var e = it.next();
      it.remove();
      String name = e.getKey(), vsn = e.getValue();
      if (!seen.add(name)) continue; // MVS-lite: first requirement wins (root deps first)
      Path dst = dir.resolve("_checkouts").resolve(name);
      if (Files.isDirectory(dst, LinkOption.NOFOLLOW_LINKS)) continue; // already vendored
      Path tar = fetchTarball(name, vsn);
      Path tmp = Files.createTempDirectory("zc-hex-" + name);
      exec(tmp, "tar", "xf", tar.toString());
      Files.createDirectories(dst);
      exec(dst, "tar", "xzf", tmp.resolve("contents.tar.gz").toString());
      System.out.println("zc: vendored " + name + " " + vsn + " (hex)");
      requirements(tmp.resolve("metadata.config")).forEach(queue::putIfAbsent);
    }
  }

  static Path fetchTarball(String name, String vsn) throws Exception {
    Path cache = Path.of(System.getProperty("user.home"), ".cache", "zinc", "hex");
    Files.createDirectories(cache);
    Path tar = cache.resolve(name + "-" + vsn + ".tar");
    if (Files.exists(tar)) return tar;
    String url = "https://repo.hex.pm/tarballs/" + name + "-" + vsn + ".tar";
    var client = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NORMAL).build();
    var resp = client.send(HttpRequest.newBuilder(URI.create(url)).build(),
                           HttpResponse.BodyHandlers.ofByteArray());
    if (resp.statusCode() != 200) die("zc: fetch " + url + " -> HTTP " + resp.statusCode());
    Files.write(tar, resp.body());
    return tar;
  }

  // requirement entries in metadata.config are proplists with keys in alphabetical order:
  // {<<"app">>,<<"cowlib">>}, {<<"optional">>,false}, {<<"requirement">>,<<"2.13.0">>}
  static final Pattern REQ = Pattern.compile(
      "\\{<<\"app\">>,<<\"([a-z0-9_]+)\">>\\},\\s*\\{<<\"optional\">>,(true|false)\\},\\s*"
          + "\\{<<\"requirement\">>,<<\"([^\"]+)\">>\\}");

  static Map<String, String> requirements(Path metadataConfig) throws IOException {
    var reqs = new LinkedHashMap<String, String>();
    Matcher m = REQ.matcher(Files.readString(metadataConfig));
    while (m.find()) {
      if (m.group(2).equals("false")) reqs.put(m.group(1), minVersion(m.group(3)));
    }
    return reqs;
  }

  // MVS: a hex requirement ("2.13.0", "~> 2.13", ">= 1.8.0") admits a minimum version;
  // build against exactly that. Reproducible without a lock file.
  static String minVersion(String req) {
    Matcher m = Pattern.compile("\\d+(\\.\\d+){0,2}").matcher(req);
    if (!m.find()) die("zc: unsupported hex requirement: " + req);
    String v = m.group();
    return v + ".0.0".substring(0, 2 * (3 - v.split("\\.").length));
  }

  // ---- build / run ----

  static void build(Path dir) throws Exception {
    var cfg = loadToml(dir);
    ensureGenerated(dir, cfg);
    vendorDeps(dir, cfg);
    exec(dir, "rebar3", "compile");
  }

  static void run(Path dir) throws Exception {
    var cmd = new ArrayList<>(List.of("erl", "-noshell"));
    for (String d : List.of("_build/default/lib", "_build/default/checkouts")) {
      Path base = dir.resolve(d);
      if (!Files.isDirectory(base)) continue;
      try (DirectoryStream<Path> apps = Files.newDirectoryStream(base)) {
        for (Path app : apps) {
          if (Files.isDirectory(app.resolve("ebin"))) {
            cmd.add("-pa");
            cmd.add(app.resolve("ebin").toString());
          }
        }
      }
    }
    cmd.add("-eval");
    cmd.add("main:run(), init:stop().");
    exec(dir, cmd.toArray(String[]::new));
  }

  static void exec(Path dir, String... cmd) throws Exception {
    var pb = new ProcessBuilder(cmd).directory(dir.toFile()).inheritIO();
    pb.environment().put("ZINC_HOME", home.toString());
    int code = pb.start().waitFor();
    if (code != 0) System.exit(code);
  }

  // ---- zinc.toml (line-based TOML subset, like zinc-go's) ----

  static Map<String, Map<String, String>> loadToml(Path dir) throws IOException {
    var cfg = new LinkedHashMap<String, Map<String, String>>();
    String section = "";
    for (String raw : Files.readAllLines(dir.resolve("zinc.toml"))) {
      String line = raw.strip();
      if (line.isEmpty() || line.startsWith("#")) continue;
      if (line.startsWith("[") && line.endsWith("]")) {
        section = line.substring(1, line.length() - 1).strip();
        continue;
      }
      int eq = line.indexOf('=');
      if (eq < 0) die("zinc.toml: bad line: " + raw);
      String key = line.substring(0, eq).strip();
      String val = line.substring(eq + 1).strip();
      if (val.startsWith("\"") && val.endsWith("\"")) val = val.substring(1, val.length() - 1);
      cfg.computeIfAbsent(section, s -> new LinkedHashMap<>()).put(key, val);
    }
    return cfg;
  }

  static void add(Path dir, String spec) throws IOException {
    int at = spec.indexOf('@');
    if (at < 0) die("usage: zc add <name@version>, e.g. zc add cowboy@2.12.0");
    String name = spec.substring(0, at);
    String ver = spec.substring(at + 1);
    Path toml = dir.resolve("zinc.toml");
    var lines = new ArrayList<>(Files.readAllLines(toml));
    String entry = name + " = \"" + ver + "\"";
    int depsAt = lines.indexOf("[deps]");
    if (depsAt < 0) {
      lines.add("");
      lines.add("[deps]");
      lines.add(entry);
    } else {
      lines.add(depsAt + 1, entry);
    }
    Files.write(toml, lines);
    System.out.println("added " + entry);
  }

  static void die(String msg) {
    System.err.println(msg);
    System.exit(1);
  }

  static void usage() {
    System.out.println("""
        usage: zc <command> [args]

          zc init <name>        create a new project (zinc.toml, src/Main.zinc)
          zc build [dir]        transpile .zinc + compile (rebar3 under the hood)
          zc run [dir]          build, then run main()
          zc clean [dir]        remove build output and generated .erl
          zc add <name@ver>     add a hex dependency to zinc.toml
          zc deps [dir]         list dependencies
          zc fmt                (not implemented yet)
          zc version            show version
        """);
  }
}
